import {StyleSheet, Platform} from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F4F6FB',
  },

  // ── HEADER ──────────────────────────────────────────────────────────────
  header: {
    backgroundColor: '#1D1E56',
    paddingTop: Platform.OS === 'ios' ? 24 : 8,
    paddingBottom: 12,
    paddingHorizontal: 20,
    zIndex: 10,
  },
  headerCircle1: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.05)',
    top: -15,
    right: 10,
  },
  headerCircle2: {
    position: 'absolute',
    width: 35,
    height: 35,
    borderRadius: 18,
    backgroundColor: 'rgba(255,214,10,0.08)',
    bottom: -8,
    left: 60,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerLogoutBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitleWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFD60A',
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: 11,
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 2,
    fontWeight: '500',
  },
  headerSpacer: {
    width: 40,
  },
  headerRefreshBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerAccentBar: {
    display: 'none',
  },

  // ── CARDS ───────────────────────────────────────────────────────────────
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 100,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginBottom: 12,
    padding: 12,
    shadowColor: '#2D3261',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.09,
    shadowRadius: 10,
    elevation: 4,
  },
  cardImageWrap: {
    width: 72,
    height: 72,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#EEF0FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  cardBody: {
    flex: 1,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  cardCategoriaBadge: {
    backgroundColor: '#F1F3F9',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  cardCategoriaText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#6B7280',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  cardPlanBadge: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  cardPlanText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  cardPlanStatus: {
    fontSize: 9,
    fontWeight: '400',
  },
  cardStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  cardStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  cardStatusLabel: {
    fontSize: 11,
    fontWeight: '700',
  },
  cardName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A1F36',
    marginBottom: 5,
    letterSpacing: 0.1,
  },
  cardInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 6,
  },
  cardInfoText: {
    fontSize: 12,
    color: '#9BA6B8',
    fontWeight: '500',
    flex: 1,
  },
  cardBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    gap: 6,
  },
  cardKmBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#EEF0FF',
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  cardKmText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#2D3261',
  },
  cardDateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  cardDateText: {
    fontSize: 10,
    fontWeight: '500',
    color: '#9BA6B8',
  },
  cardArrow: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFD60A',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },

  // ── EMPTY ────────────────────────────────────────────────────────────────
  emptyWrap: {
    alignItems: 'center',
    paddingTop: 80,
    gap: 12,
  },
  emptyText: {
    fontSize: 14,
    color: '#9BA6B8',
    fontWeight: '500',
  },

  // ── RESULTS COUNT ───────────────────────────────────────────────────────
  resultsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 4,
    gap: 6,
  },
  resultsText: {
    fontSize: 12,
    color: '#9BA6B8',
    fontWeight: '500',
  },
  resultsCount: {
    fontSize: 12,
    color: '#2D3261',
    fontWeight: '700',
  },

  // ── SEARCH BAR ──────────────────────────────────────────────────────────
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
    backgroundColor: '#F4F6FB',
  },
  searchInputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    gap: 10,
    shadowColor: '#2D3261',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#1A1F36',
    padding: 0,
    fontWeight: '500',
  },
  searchFilterBtn: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2D3261',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  searchFilterBtnActive: {
    backgroundColor: '#2D3261',
  },
  searchFilterBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FFD60A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchFilterBadgeText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#2D3261',
  },

  // ── ACTIVE FILTER CHIP ─────────────────────────────────────────────────
  activeFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginHorizontal: 20,
    marginBottom: 8,
    backgroundColor: '#EEF0FF',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    gap: 6,
    borderWidth: 1,
    borderColor: '#C7CBEF',
  },
  activeFilterChipText: {
    fontSize: 12,
    color: '#2D3261',
    fontWeight: '600',
    maxWidth: 200,
  },

  // ── FAB FILTER ──────────────────────────────────────────────────────────
  fab: {
    position: 'absolute',
    right: 18,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FFD60A',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2D3261',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 10,
  },

  // ── FAB BADGE ───────────────────────────────────────────────────────────
  fabBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#2D3261',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fabBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#FFD60A',
  },

  // ── MODAL ───────────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5,30,71,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 44 : 28,
  },
  modalHandle: {
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E0E4EF',
    alignSelf: 'center',
    marginBottom: 22,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A1F36',
  },
  modalSubtitle: {
    fontSize: 12,
    color: '#9BA6B8',
    fontWeight: '500',
    marginTop: 2,
  },
  modalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F4F6FB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalSectionLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#2D3261',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  modalInput: {
    borderWidth: 1.5,
    borderColor: '#E0E4EF',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 13,
    fontSize: 14,
    color: '#1A1F36',
    backgroundColor: '#F8F9FD',
  },
  modalChipRow: {
    flexDirection: 'row',
    gap: 10,
  },
  modalChipRowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  modalChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: '#F4F6FB',
    borderWidth: 1.5,
    borderColor: '#E0E4EF',
  },
  modalChipWrap: {
    flex: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#F4F6FB',
    borderWidth: 1.5,
    borderColor: '#E0E4EF',
  },
  modalChipActive: {
    backgroundColor: '#1D1E56',
    borderColor: '#1D1E56',
  },
  modalChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6B7280',
  },
  modalChipTextActive: {
    color: '#FFFFFF',
  },
  modalStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  modalDateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    paddingVertical: 11,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#F4F6FB',
    borderWidth: 1.5,
    borderColor: '#E0E4EF',
  },
  modalDateBtnActive: {
    backgroundColor: '#2D3261',
    borderColor: '#2D3261',
  },
  modalDateBtnText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: '#6B7280',
  },
  modalDateBtnTextActive: {
    color: '#FFFFFF',
  },
  modalDateBtnClear: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 6,
  },

  modalBtnRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 28,
  },
  modalBtnClear: {
    flex: 1,
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
    backgroundColor: '#F4F6FB',
    borderWidth: 1.5,
    borderColor: '#E0E4EF',
  },
  modalBtnClearText: {
    color: '#6B7280',
    fontSize: 14,
    fontWeight: '700',
  },
  modalBtnApply: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1D1E56',
  },
  modalBtnApplyText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
});

export default styles;
