import {StyleSheet} from 'react-native';
import {windowWidth, windowHeight} from '../../../themes/appConstant';
import appColors from '../../../themes/appColors';

const LIST_PADDING_HORIZONTAL = 24;
const CARD_MARGIN_VERTICAL = windowHeight(2.2);
const CARD_PADDING_H = windowWidth(6);
const CARD_PADDING_V = windowHeight(2.8);

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: windowWidth(6),
    paddingTop: windowHeight(4),
    paddingBottom: windowHeight(3),
  },
  headerBack: {
    padding: 8,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 8,
  },
  headerIcon: {
    padding: 4,
  },
  listContent: {
    paddingLeft: LIST_PADDING_HORIZONTAL,
    paddingRight: LIST_PADDING_HORIZONTAL,
    paddingTop: windowHeight(2),
    paddingBottom: windowHeight(4),
  },
  emptyListContent: {
    flexGrow: 1,
    paddingLeft: LIST_PADDING_HORIZONTAL,
    paddingRight: LIST_PADDING_HORIZONTAL,
    paddingTop: windowHeight(10),
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardTouchable: {
    width: '100%',
  },
  card: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingBottom: CARD_PADDING_V,
    paddingLeft: CARD_PADDING_H,
    paddingRight: CARD_PADDING_H,
    marginTop: CARD_MARGIN_VERTICAL,
    marginBottom: CARD_MARGIN_VERTICAL,
    borderWidth: 1,
    borderColor: '#DEE0E4',
    overflow: 'hidden',
  },
  cardHeaderWrap: {
    backgroundColor: '#F0F2F7',
    paddingHorizontal: CARD_PADDING_H,
    paddingTop: CARD_PADDING_V,
    paddingBottom: CARD_PADDING_V,
    marginLeft: -CARD_PADDING_H,
    marginRight: -CARD_PADDING_H,
    marginBottom: 0,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: windowHeight(1.5),
  },
  cardHeaderLeft: {
    flex: 1,
    minWidth: 0,
  },
  cardPlateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  cardYearTagMargin: {
    marginLeft: 10,
  },
  cardPlateText: {
    fontSize: 18,
    fontWeight: '700',
  },
  cardYearTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#D4E0F7',
  },
  cardYearTagText: {
    fontSize: 12,
    fontWeight: '700',
    color: appColors.primary,
  },
  cardIconTopRight: {
    minWidth: 44,
    minHeight: 44,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#D4E0F7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardModelText: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  cardColorText: {
    fontSize: 13,
    opacity: 0.75,
  },
  cardSeparator: {
    height: 1,
    backgroundColor: '#DEE0E4',
    marginVertical: windowHeight(2),
    marginHorizontal: 0,
  },
  cardBody: {
    paddingHorizontal: 0,
  },
  cardDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: windowHeight(8),
  },
  cardDetailIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#D4E0F7',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  cardDetailBody: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardDetailLabel: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    color: '#9BA6B8',
  },
  cardDetailValue: {
    fontSize: 14,
    fontWeight: '700',
  },
  cardDetailChevron: {
    marginLeft: 4,
    opacity: 0.6,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: windowHeight(12),
    paddingHorizontal: windowWidth(10),
    marginBottom: windowHeight(100),
  },
  emptyIconWrap: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#E8ECF4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: windowHeight(3),
  },
  emptyText: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: windowHeight(1.5),
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  emptySubtext: {
    fontSize: 15,
    opacity: 0.85,
    textAlign: 'center',
    paddingHorizontal: 24,
    lineHeight: 22,
  },
  actionModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: windowWidth(8),
  },
  actionModalBox: {
    width: '85%',
    maxWidth: 400,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 28,
    paddingHorizontal: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 12,
  },
  actionModalHeaderIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#EEF4FF',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  actionModalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1A1D26',
    textAlign: 'center',
    marginBottom: 8,
  },
  actionModalSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 28,
  },
  actionButtonsRow: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  actionBtnEdit: {
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 16,
    backgroundColor: '#EEF4FF',
    borderWidth: 1,
    borderColor: '#E0E7FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  actionBtnEditIconWrap: {
    marginBottom: 8,
  },
  actionBtnEditText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1D26',
  },
  actionBtnDelete: {
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 16,
    backgroundColor: '#FFF1F0',
    borderWidth: 1,
    borderColor: '#FFE4E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  actionBtnDeleteIconWrap: {
    marginBottom: 8,
  },
  actionBtnDeleteText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1D26',
  },
  actionModalCerrar: {
    marginTop: 8,
    paddingVertical: 10,
    alignItems: 'center',
  },
  actionModalCerrarText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  // Modal "Plan de pago requerido"
  planModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: windowWidth(8),
  },
  planModalCard: {
    width: '90%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 32,
    paddingHorizontal: 28,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.28,
    shadowRadius: 24,
    elevation: 16,
  },
  planModalIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: appColors.primary ?? '#2D3261',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  planModalTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1A1D26',
    textAlign: 'center',
    marginBottom: 12,
    paddingHorizontal: 8,
  },
  planModalMessage: {
    fontSize: 15,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 28,
    paddingHorizontal: 4,
  },
  planModalBtn: {
    backgroundColor: appColors.primary ?? '#2D3261',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 14,
    minWidth: 160,
    alignItems: 'center',
  },
  planModalBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  planModalCerrar: {
    marginTop: 16,
    paddingVertical: 8,
    alignItems: 'center',
  },
  planModalCerrarText: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '500',
  },
  // Modal "Planes disponibles"
  plansModalCard: {
    width: '90%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 24,
    paddingHorizontal: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.28,
    shadowRadius: 24,
    elevation: 16,
  },
  plansModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  plansModalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1A1D26',
  },
  plansModalCloseBtn: {
    padding: 4,
  },
  planItemCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 20,
  },
  planItemBadge: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 8,
  },
  planItemPrice: {
    fontSize: 28,
    fontWeight: '800',
    color: appColors.primary ?? '#2D3261',
  },
  planItemPeriod: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '600',
    marginLeft: 4,
  },
  planItemVehicles: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1D26',
    marginBottom: 6,
  },
  planItemDesc: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
  },
});

export default styles;
