import {Platform, StyleSheet} from 'react-native';
import {windowWidth, windowHeight} from '../../../themes/appConstant';
import appColors from '../../../themes/appColors';

const LIST_PADDING_HORIZONTAL = 24;
const CARD_MARGIN_VERTICAL = windowHeight(2.2);
const CARD_PADDING_H = windowWidth(6);
const CARD_PADDING_V = windowHeight(2.8);

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  vehiclesTopHeader: {
    backgroundColor: '#1F2344',
    paddingTop: windowHeight(3.8),
    paddingBottom: windowHeight(4.6),
    paddingHorizontal: windowWidth(5),
    justifyContent: 'center',
    overflow: 'hidden',
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    borderBottomWidth: 7,
    borderBottomColor: '#FFD60A',
    position: 'relative',
  },
  vehiclesHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  vehiclesHeaderCenter: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 0,
    width: '100%',
  },
  vehiclesHeaderCircle1: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(255,214,10,0.12)',
    top: -34,
    right: -22,
  },
  vehiclesHeaderCircle2: {
    position: 'absolute',
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(255,255,255,0.10)',
    top: 30,
    left: -14,
  },
  vehiclesHeaderBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,214,10,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: windowHeight(1.4),
    left: windowWidth(4),
    zIndex: 3,
  },
  vehiclesHeaderTitle: {
    textAlign: 'center',
    fontSize: 32,
    fontWeight: '900',
    color: '#FFD60A',
    marginBottom: 6,
  },
  vehiclesHeaderSubtitle: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
    opacity: 0.88,
    lineHeight: 20,
    paddingHorizontal: 52,
    maxWidth: '100%',
  },
  driverDocsEntryBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: LIST_PADDING_HORIZONTAL,
    marginTop: 14,
    marginBottom: 4,
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E8ECF4',
    shadowColor: '#0F172A',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 4,
  },
  driverDocsEntryBannerIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFD60A',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(31,35,68,0.08)',
  },
  driverDocsEntryBannerTextCol: {
    flex: 1,
    marginLeft: 14,
    marginRight: 8,
    minWidth: 0,
  },
  driverDocsEntryBannerTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1F2344',
    letterSpacing: -0.2,
  },
  driverDocsEntryBannerSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 4,
    lineHeight: 18,
  },
  driverDocsEntryBannerChevron: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehiclesHeaderRightSpacer: {
    width: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: windowWidth(6),
    paddingTop: windowHeight(4),
    paddingBottom: windowHeight(3),
  },
  headerBack: {
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 8,
  },
  headerRightSpacer: {
    width: windowWidth(10),
    height: 1,
  },
  headerAddBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: '#1F2344',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerAddText: {
    color: '#FFD60A',
    fontSize: 13,
    fontWeight: '800',
    marginLeft: 6,
  },
  listContent: {
    paddingLeft: LIST_PADDING_HORIZONTAL,
    paddingRight: LIST_PADDING_HORIZONTAL,
    paddingTop: windowHeight(1.2),
    paddingBottom: windowHeight(4),
  },
  listContentWithFooter: {
    paddingLeft: LIST_PADDING_HORIZONTAL,
    paddingRight: LIST_PADDING_HORIZONTAL,
    paddingTop: windowHeight(1.2),
    paddingBottom: windowHeight(16),
  },
  emptyListContent: {
    flexGrow: 1,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  stickyFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: windowWidth(5),
    paddingTop: 10,
    paddingBottom: 18,
    backgroundColor: 'rgba(245, 246, 248, 0.98)',
    borderTopWidth: 1,
    borderTopColor: '#E6ECFA',
  },
  stickyAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 60,
    borderRadius: 16,
    backgroundColor: '#1F2344',
  },
  stickyAddIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FFD60A',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  stickyAddButtonText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardTouchable: {
    width: '100%',
    marginTop: 30,
  },
  card: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingBottom: CARD_PADDING_V,
    paddingLeft: CARD_PADDING_H,
    paddingRight: CARD_PADDING_H,
    marginTop: windowHeight(2.4),
    marginBottom: windowHeight(1.6),
    borderWidth: 1,
    borderColor: '#E3E8F4',
    overflow: 'hidden',
    shadowColor: '#1F2344',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 6,
  },
  cardHeaderWrap: {
    backgroundColor: '#1F2344',
    paddingHorizontal: CARD_PADDING_H,
    paddingTop: CARD_PADDING_V,
    paddingBottom: CARD_PADDING_V,
    marginLeft: -CARD_PADDING_H,
    marginRight: -CARD_PADDING_H,
    marginBottom: 0,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: windowHeight(1.5),
  },
  cardHeaderLeft: {
    flex: 1,
    minWidth: 0,
  },
  cardPlateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  cardMetaTagMargin: {
    marginLeft: 10,
  },
  cardPlateText: {
    fontSize: 18,
    fontWeight: '700',
  },
  cardYearTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  cardYearTagText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  cardIconTopRight: {
    minWidth: 44,
    minHeight: 44,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.16)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardModelText: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  cardColorText: {
    fontSize: 13,
    opacity: 0.92,
  },
  cardHeaderFlagsInline: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginTop: 6,
  },
  cardHeaderFlagWarn: {
    fontSize: 10,
    fontWeight: '800',
    color: 'rgba(255,180,180,0.95)',
    letterSpacing: 0.2,
  },
  cardHeaderFlagOk: {
    fontSize: 10,
    fontWeight: '800',
    color: 'rgba(255,214,10,0.95)',
    letterSpacing: 0.2,
  },
  cardHeaderFlagSep: {
    marginLeft: 8,
  },
  cardSeparator: {
    height: 1,
    backgroundColor: '#E6ECFA',
    marginVertical: windowHeight(2),
    marginHorizontal: 0,
  },
  cardBody: {
    paddingHorizontal: 0,
  },
  cardDocExpiryStrip: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'stretch',
    gap: 10,
    marginBottom: 10,
    marginTop: -2,
  },
  cardDocExpiryCardWrap: {
    flex: 1,
    minWidth: 0,
  },
  cardDocExpiryCard: {
    width: '100%',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    paddingLeft: 11,
    borderRadius: 14,
    minHeight: 72,
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#0f172a',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.07,
        shadowRadius: 8,
      },
      android: {
        elevation: 3,
      },
      default: {},
    }),
  },
  cardDocExpiryPillExpired: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: 'rgba(252, 165, 165, 0.55)',
    borderLeftWidth: 4,
    borderLeftColor: '#DC2626',
  },
  cardDocExpiryPillSoon: {
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: 'rgba(253, 230, 138, 0.7)',
    borderLeftWidth: 4,
    borderLeftColor: '#D97706',
  },
  cardDocExpiryPillOk: {
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: 'rgba(167, 243, 208, 0.65)',
    borderLeftWidth: 4,
    borderLeftColor: '#16A34A',
  },
  cardDocExpiryCardTitle: {
    fontSize: 10,
    fontWeight: '800',
    color: '#64748B',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  cardDocExpiryCardDate: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1E293B',
    letterSpacing: -0.2,
    marginBottom: 4,
  },
  cardDocExpiryCardStatus: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.15,
    lineHeight: 15,
  },
  cardDocExpiryTextExpired: {
    color: '#B91C1C',
  },
  cardDocExpiryTextSoon: {
    color: '#C2410C',
  },
  cardDocExpiryTextOk: {
    color: '#15803D',
  },
  cardNotifSection: {
    backgroundColor: '#FAFBFF',
    borderWidth: 1,
    borderColor: '#E4EBFA',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  cardNotifHeaderRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 8,
    justifyContent: 'space-between',
  },
  cardNotifTitleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
    marginBottom: 2,
    flexShrink: 0,
  },
  cardNotifTitle: {
    marginLeft: 8,
    fontSize: 11,
    fontWeight: '900',
    color: '#64748B',
    letterSpacing: 0.3,
  },
  cardNotifPillsInline: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    marginBottom: 2,
  },
  cardNotifAlertStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 2,
  },
  cardNotifAlertPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginRight: 6,
    marginBottom: 4,
  },
  cardNotifAlertPillDanger: {
    backgroundColor: 'rgba(229,57,53,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(229,57,53,0.35)',
  },
  cardNotifAlertPillWarn: {
    backgroundColor: 'rgba(249,168,37,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(249,168,37,0.45)',
  },
  cardNotifAlertPillOk: {
    backgroundColor: 'rgba(46,125,50,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(46,125,50,0.35)',
  },
  cardNotifAlertPillText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  cardNotifAlertPillTextDanger: {
    color: '#C62828',
  },
  cardNotifAlertPillTextWarn: {
    color: '#E65100',
  },
  cardNotifAlertPillTextOk: {
    color: '#2E7D32',
  },
  cardNotifStats: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1F2344',
    marginBottom: 4,
  },
  cardNotifMuted: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '600',
    lineHeight: 17,
  },
  cardNotifPreviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  cardNotifDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#2E7D32',
    marginRight: 8,
  },
  cardNotifPreviewText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    color: '#2D3261',
  },
  cardNotifMore: {
    marginTop: 6,
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
  },
  cardNotifVerMasBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    alignSelf: 'stretch',
    marginTop: 0,
    paddingVertical: 6,
    paddingHorizontal: 0,
  },
  cardNotifVerMasText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#2563EB',
    marginRight: 2,
  },
  cardNotifItemWrap: {
    marginBottom: 0,
  },
  cardNotifItemName: {
    fontSize: 13,
    fontWeight: '900',
    color: '#1F2344',
    marginBottom: 8,
    lineHeight: 18,
  },
  cardGridRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  cardMiniInfo: {
    flex: 1,
    backgroundColor: '#F8FAFD',
    borderWidth: 1,
    borderColor: '#E7ECF7',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  cardMiniInfoLeft: {
    marginRight: 8,
  },
  cardMiniInfoLabel: {
    fontSize: 11,
    color: '#7B879B',
    marginBottom: 4,
    fontWeight: '700',
  },
  cardMiniInfoValue: {
    fontSize: 13,
    color: '#1F2344',
    fontWeight: '800',
  },
  cardDetailGridRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: windowHeight(2),
  },
  cardDetailHalf: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    minWidth: 0,
  },
  cardDetailHalfLeft: {
    marginRight: 8,
    paddingRight: 4,
  },
  cardDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: windowHeight(8),
  },
  cardDetailIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1F2344',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  cardDetailBody: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardDetailLabel: {
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.5,
    color: '#9BA6B8',
  },
  cardDetailValue: {
    fontSize: 14,
    fontWeight: '700',
  },
  cardDetailChevron: {
    marginLeft: 4,
    opacity: 0.6,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: windowHeight(12),
    paddingHorizontal: windowWidth(10),
    marginBottom: windowHeight(100),
  },
  emptyStateContainer: {
    flex: 1,
    width: '100%',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    paddingHorizontal: 0,
  },
  emptyHero: {
    width: '100%',
    backgroundColor: '#1F2344',
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    paddingTop: 28,
    paddingBottom: 78,
    alignItems: 'center',
    overflow: 'hidden',
    borderBottomWidth: 8,
    borderBottomColor: '#FFD60A',
  },
  emptyHeroInner: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  emptyHeroTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 40,
    marginBottom: 10,
  },
  emptyHeroSubtitle: {
    fontSize: 18,
    color: '#E5E7EB',
    textAlign: 'center',
    lineHeight: 24,
  },
  emptyCard: {
    width: '80%',
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: '#EEF2FF',
  },
  emptyCardItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  emptyCardItemTextWrap: {
    marginLeft: 10,
    flex: 1,
  },
  emptyCardItemTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: '#1F2344',
    marginBottom: 2,
  },
  emptyCardItemSubtitle: {
    fontSize: 16,
    color: '#1F2344',
  },
  emptyPrimaryButton: {
    marginTop: -15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 18,
    backgroundColor: '#1F2344',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
    width: '80%',
    alignSelf: 'center',
    height: 68,
  },
  emptyPrimaryIconWrap: {
    width: 45,
    height: 45,
    borderRadius: 45,
    backgroundColor: '#FFD60A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  emptyPrimaryText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  emptyIconWrap: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#E8ECF4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: windowHeight(3),
  },
  emptyText: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: windowHeight(1.5),
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  emptySubtext: {
    fontSize: 15,
    opacity: 0.85,
    textAlign: 'center',
    paddingHorizontal: 24,
    lineHeight: 22,
  },
  actionModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: windowWidth(8),
  },
  actionModalBox: {
    width: '85%',
    maxWidth: 400,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 28,
    paddingHorizontal: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 12,
  },
  actionModalHeaderIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#EEF4FF',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  actionModalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1A1D26',
    textAlign: 'center',
    marginBottom: 8,
  },
  actionModalSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 28,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingHorizontal: 2,
  },
  actionBtnEdit: {
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 8,
    backgroundColor: '#EEF4FF',
    borderWidth: 1,
    borderColor: '#E0E7FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    width: 102,
  },
  actionBtnEditIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#DCE9FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  actionBtnEditText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#1A1D26',
    textAlign: 'center',
  },
  actionBtnInfo: {
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 8,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    width: 102,
  },
  actionBtnInfoIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#E8EEF8',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  actionBtnInfoText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#1A1D26',
    textAlign: 'center',
  },
  actionBtnDelete: {
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 8,
    backgroundColor: '#FFF1F0',
    borderWidth: 1,
    borderColor: '#FFE4E2',
    alignItems: 'center',
    justifyContent: 'center',
    width: 102,
  },
  actionBtnDeleteIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#FFE4E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  actionBtnDeleteText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#1A1D26',
    textAlign: 'center',
  },
  actionModalCerrar: {
    marginTop: 8,
    paddingVertical: 10,
    alignItems: 'center',
  },
  actionModalCerrarText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  // Modal "Plan de pago requerido"
  planModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: windowWidth(8),
  },
  planModalCard: {
    width: '90%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 32,
    paddingHorizontal: 28,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.28,
    shadowRadius: 24,
    elevation: 16,
  },
  planModalIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: appColors.primary ?? '#2D3261',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  planModalTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1A1D26',
    textAlign: 'center',
    marginBottom: 12,
    paddingHorizontal: 8,
  },
  planModalMessage: {
    fontSize: 15,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 28,
    paddingHorizontal: 4,
  },
  planModalBtn: {
    backgroundColor: appColors.primary ?? '#2D3261',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 14,
    minWidth: 160,
    alignItems: 'center',
  },
  planModalBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  planModalCerrar: {
    marginTop: 16,
    paddingVertical: 8,
    alignItems: 'center',
  },
  planModalCerrarText: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '500',
  },
  // Modal "Planes disponibles"
  plansModalCard: {
    width: '90%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 24,
    paddingHorizontal: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.28,
    shadowRadius: 24,
    elevation: 16,
  },
  plansModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  plansModalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1A1D26',
  },
  plansModalCloseBtn: {
    padding: 4,
  },
  planItemCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 20,
  },
  planItemBadge: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 8,
  },
  planItemPrice: {
    fontSize: 28,
    fontWeight: '800',
    color: appColors.primary ?? '#2D3261',
  },
  planItemPeriod: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '600',
    marginLeft: 4,
  },
  planItemVehicles: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1D26',
    marginBottom: 6,
  },
  planItemDesc: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
  },
  // Modal documentos conductor (licencia + certificado médico)
  driverDocsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 18, 42, 0.72)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: windowWidth(5),
    paddingVertical: 24,
  },
  /** Capa encima del contenido del modal documentos (evita segundo Modal nativo detrás). */
  driverDocsDatePickerLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20000,
    elevation: 20000,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  /** Vista previa de foto dentro del mismo Modal (evita segundo Modal nativo, que falla con transparent encima). */
  driverDocsFullPreviewLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 25000,
    elevation: 25000,
    backgroundColor: '#000000',
    flexDirection: 'column',
  },
  driverDocsModalCard: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '88%',
    flexDirection: 'column',
    flexShrink: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 26,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E8ECF4',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 16},
    shadowOpacity: 0.22,
    shadowRadius: 28,
    elevation: 20,
  },
  driverDocsModalScroll: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
  },
  driverDocsModalLoadingWrap: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 160,
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverDocsModalLoadingText: {
    marginTop: 12,
    color: '#64748B',
    fontWeight: '600',
    fontSize: 14,
  },
  driverDocsModalHero: {
    flexShrink: 0,
    backgroundColor: '#1F2344',
    paddingTop: 22,
    paddingBottom: 20,
    paddingHorizontal: 20,
    alignItems: 'center',
    borderBottomWidth: 4,
    borderBottomColor: '#FFD60A',
  },
  driverDocsModalHeroIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: 'rgba(255,214,10,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  driverDocsModalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  driverDocsModalSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.82)',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 18,
    paddingHorizontal: 8,
  },
  driverDocsScroll: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 24,
  },
  driverDocsSection: {
    marginBottom: 22,
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  driverDocsSectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1F2344',
    marginBottom: 4,
  },
  driverDocsSectionHint: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
    marginBottom: 12,
  },
  driverDocsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  driverDocsSlot: {
    flex: 1,
    marginRight: 10,
  },
  driverDocsSlotLast: {
    flex: 1,
    marginRight: 0,
  },
  driverDocsLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
    marginBottom: 6,
  },
  driverDocsPickBtn: {
    width: '100%',
    height: 100,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    borderStyle: 'dashed',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  driverDocsPickBtnFilled: {
    borderStyle: 'solid',
    borderColor: '#1F2344',
  },
  driverDocsPickText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
    textAlign: 'center',
    paddingHorizontal: 6,
  },
  driverDocsThumbWrap: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  driverDocsThumb: {
    width: '100%',
    height: '100%',
  },
  driverDocsThumbHit: {
    ...StyleSheet.absoluteFillObject,
  },
  driverDocsExpandPhotoBtn: {
    position: 'absolute',
    left: 6,
    bottom: 6,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(31, 35, 68, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 4,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 10, 0.45)',
  },
  driverDocsChangePhotoBtn: {
    position: 'absolute',
    right: 6,
    bottom: 6,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(31, 35, 68, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 4,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 10, 0.45)',
  },
  driverDocsRemoveX: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#1F2344',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 10, 0.45)',
  },
  driverDocsDateBtn: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: '#FFFFFF',
  },
  driverDocsDateText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2344',
  },
  driverDocsDatePlaceholder: {
    color: '#94A3B8',
    fontWeight: '500',
  },
  driverDocsInfoBox: {
    marginBottom: 14,
    padding: 14,
    borderRadius: 14,
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#C7D2FE',
  },
  driverDocsInfoTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#312E81',
    marginBottom: 8,
  },
  driverDocsInfoText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4338CA',
    lineHeight: 19,
  },
  driverDocsFullPreviewFooter: {
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingTop: 14,
    paddingBottom: 16,
    backgroundColor: 'rgba(0,0,0,0.92)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,214,10,0.25)',
  },
  driverDocsFullPreviewClose: {
    width: '100%',
    maxWidth: 340,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,214,10,0.35)',
  },
  driverDocsFullPreviewCloseText: {
    color: '#FFD60A',
    fontWeight: '800',
    fontSize: 15,
  },
  driverDocsFullPreviewBody: {
    flex: 1,
    minHeight: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000000',
  },
  driverDocsFullPreviewImage: {
    width: '100%',
    flex: 1,
  },
  driverDocsTogglePhotos: {
    alignSelf: 'flex-start',
    marginBottom: 4,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  driverDocsTogglePhotosInner: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  driverDocsTogglePhotosText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2563EB',
    textDecorationLine: 'underline',
    marginRight: 6,
  },
  driverDocsFooter: {
    flexDirection: 'row',
    gap: 10,
    flexShrink: 0,
    marginTop: 8,
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: '#EEF2F7',
    backgroundColor: '#FFFFFF',
  },
  driverDocsBtnSecondary: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
  },
  driverDocsBtnSecondaryText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#475569',
  },
  driverDocsBtnPrimary: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#1F2344',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFD60A',
  },
  driverDocsBtnPrimaryDisabled: {
    opacity: 0.42,
    borderColor: 'rgba(255, 214, 10, 0.35)',
  },
  driverDocsBtnPrimaryText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFD60A',
  },
  driverDocsBtnPrimaryTextDisabled: {
    color: 'rgba(255, 214, 10, 0.75)',
  },
});

export default styles;
