import {StyleSheet} from 'react-native';
import appColors from '../../../themes/appColors';
import {
  fontSizes,
  windowHeight,
  windowWidth,
} from '../../../themes/appConstant';
import {external} from '../../../style/external.css';
import appFonts from '../../../themes/appFonts';
import {commonStyles} from '../../../style/commonStyle.css';

const styles = StyleSheet.create({
  newArrivalContainer: {
    ...external.ph_20,
    paddingBottom: windowHeight(2),
  },
  listContent: {
    paddingTop: windowHeight(1),
  },
  separator: {
    height: windowHeight(12),
  },
  cardOuter: {
    width: '100%',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E8ECF5',
    shadowColor: '#1F2344',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  cardImageSection: {
    width: '100%',
    height: windowHeight(38),
    backgroundColor: '#F3F5FB',
    position: 'relative',
  },
  cardImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  certFloating: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: '#FFD60A',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: 'rgba(9,13,46,0.15)',
  },
  cardContent: {
    paddingHorizontal: windowWidth(4),
    paddingTop: windowHeight(12),
    paddingBottom: windowHeight(12),
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 10,
    gap: 8,
  },
  cardTitle: {
    flex: 1,
    fontSize: fontSizes.FONT19,
    fontFamily: appFonts.semiBold,
    fontWeight: '700',
    lineHeight: 24,
    color: appColors.titleText,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBF0',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#FFE6A8',
  },
  ratingText: {
    ...commonStyles.subtitleText,
    marginLeft: 4,
    color: '#B45309',
    fontFamily: appFonts.bold,
    fontWeight: '700',
    fontSize: fontSizes.FONT14,
  },
  metaBlock: {
    gap: 6,
    marginBottom: 12,
  },
  metaLine: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaIcon: {
    marginRight: 6,
    width: 14,
  },
  metaText: {
    flex: 1,
    fontSize: fontSizes.FONT13,
    lineHeight: 18,
    color: '#64748B',
    fontFamily: appFonts.Regular,
    fontWeight: '500',
  },
  publishedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 2,
  },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  statusPillActive: {
    backgroundColor: '#DCFCE7',
  },
  statusPillInactive: {
    backgroundColor: '#F1F5F9',
  },
  statusPillText: {
    fontSize: fontSizes.FONT12,
    fontWeight: '800',
  },
  statusPillTextActive: {
    color: '#166534',
  },
  statusPillTextInactive: {
    color: '#64748B',
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#EEF2F7',
  },
  verMas: {
    fontSize: fontSizes.FONT14,
    color: '#2D3261',
    fontWeight: '800',
    textDecorationLine: 'underline',
  },
  priceTag: {
    backgroundColor: '#1F2344',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFD60A',
  },
  priceValue: {
    fontSize: fontSizes.FONT18,
    color: '#FFD60A',
    fontFamily: appFonts.semiBold,
    fontWeight: '800',
  },
  container: {
    marginTop: windowHeight(13),
    flexDirection: 'row',
    padding: windowHeight(1),
    borderRadius: windowHeight(10),
    overflow: 'hidden',
    elevation: 1.5,
    margin: 1,
  },
  imageContainer: {
    height: windowHeight(70),
    width: windowWidth(108),
    backgroundColor: '#F3F5FB',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    width: windowWidth(76),
    height: windowHeight(45),
    resizeMode: 'contain',
  },
  textContainer: {
    ...external.mh_8,
  },
  title: {
    width: '75%',
    color: appColors.titleText,
    fontSize: fontSizes.FONT19,
    fontFamily: appFonts.semiBold,
    fontWeight: '600',
  },
  ratingContainer: {
    ...external.fd_row,
    ...external.ai_center,
  },
  subtitle: {
    ...commonStyles.subtitleText,
  },
  datoSub: {
    fontWeight: '400',
    fontSize: fontSizes.FONT13,
    lineHeight: windowHeight(18),
    color: '#9BA6B8',
    fontFamily: appFonts.Regular,
  },
  priceContainer: {
    ...external.fd_row,
    ...external.ai_center,
    ...external.mt_5,
  },
  price: {
    ...commonStyles.titleText19,
    fontSize: fontSizes.FONT21,
    fontFamily: appFonts.semiBold,
    fontWeight: '600',
  },
  status: {
    ...commonStyles.titleText10,
    fontSize: fontSizes.FONT15,
  },
  underlinePrice: {
    ...commonStyles.subtitleText,
    ...external.mh_2,
    textDecorationLine: 'line-through',
  },
  linearBorderStyle: {
    width: windowHeight(25),
    height: windowHeight(25),
    borderRadius: windowHeight(25),
    alignItems: 'center',
    justifyContent: 'center',
  },
  showLinear: {
    width: 40,
    backgroundColor: appColors.bgLayer,
    position: 'absolute',
    right: 0,
    bottom: -20,
    borderRadius: 20,
    alignItems: 'center',
    paddingVertical: 5,
  },
  menuItemContent: {
    width: '100%',
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: windowHeight(10),
    paddingVertical: windowHeight(10),
    borderRadius: windowHeight(10),
  },
  /** Tarjeta de servicio (lista horizontal original, solo UI) */
  serviceRowOuter: {
    marginTop: windowHeight(12),
    marginHorizontal: 0,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#1F2344',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 5,
  },
  serviceRowInner: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 24,
    borderWidth: 1,
    position: 'relative',
  },
  thumbWrap: {
    position: 'relative',
    alignSelf: 'flex-start',
  },
  certBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    zIndex: 2,
    backgroundColor: '#FFD60A',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: 'rgba(9,13,46,0.2)',
  },
  serviceThumb: {
    width: 104,
    height: 104,
    borderRadius: 18,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  publicadoImageBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    zIndex: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    maxWidth: '92%',
  },
  publicadoImageBadgeOn: {
    backgroundColor: '#DCFCE7',
  },
  publicadoImageBadgeOff: {
    backgroundColor: '#F1F5F9',
  },
  publicadoImageBadgeText: {
    fontSize: fontSizes.FONT10,
    fontFamily: appFonts.bold,
    fontWeight: '800',
  },
  publicadoImageBadgeTextOn: {
    color: '#166534',
  },
  publicadoImageBadgeTextOff: {
    color: '#64748B',
  },
  serviceThumbImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  serviceTextCol: {
    flex: 1,
    minWidth: 0,
    marginStart: 12,
    justifyContent: 'flex-start',
  },
  serviceTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 10,
    gap: 8,
  },
  serviceTitleText: {
    flex: 1,
    fontSize: fontSizes.FONT19,
    fontFamily: appFonts.semiBold,
    fontWeight: '600',
    lineHeight: 24,
  },
  serviceTitleRatingRow: {
    width: '100%',
    alignItems: 'flex-start',
    gap: 8,
  },
  serviceTitleHero: {
    flex: 1,
    minWidth: 0,
    fontSize: fontSizes.FONT17,
    fontFamily: appFonts.bold,
    fontWeight: '900',
    lineHeight: 22,
    marginTop: 0,
    letterSpacing: 0.2,
  },
  ratingCornerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#FFD60A',
    borderWidth: 1,
    borderColor: '#E7BF00',
  },
  ratingCornerPillDark: {
    backgroundColor: '#EAB308',
    borderColor: '#CA8A04',
  },
  ratingCornerPillText: {
    fontSize: fontSizes.FONT14,
    fontFamily: appFonts.bold,
    fontWeight: '700',
    color: '#1F2344',
  },
  ratingCornerPillTextDark: {
    color: '#0F172A',
  },
  ratingRowSimple: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  ratingSimpleValue: {
    fontSize: fontSizes.FONT14,
    fontFamily: appFonts.semiBold,
    fontWeight: '600',
  },
  tagChipCategoryLavender: {
    backgroundColor: '#EDE9FE',
    borderColor: '#DDD6FE',
  },
  tagChipTextLavender: {
    color: '#5B21B6',
  },
  metaStack: {
    width: '100%',
    maxWidth: '100%',
    gap: 8,
    marginTop: 2,
    marginBottom: 2,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 4,
    marginBottom: 0,
  },
  tagRowBelowTitle: {
    marginTop: 0,
  },
  serviceDescStack: {
    marginTop: 8,
    width: '100%',
    gap: 4,
  },
  serviceDescLabel: {
    fontSize: fontSizes.FONT10,
    fontFamily: appFonts.bold,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  serviceDescSnippet: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.semiBold,
    fontWeight: '500',
    lineHeight: 17,
  },
  servicePublicadoChip: {
    flexShrink: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  servicePublicadoChipSi: {
    backgroundColor: '#F0FDF4',
    borderColor: '#22C55E',
  },
  servicePublicadoChipSiDark: {
    backgroundColor: 'rgba(34, 197, 94, 0.18)',
    borderColor: '#4ADE80',
  },
  servicePublicadoChipNo: {
    backgroundColor: '#FFFBEB',
    borderColor: '#EAB308',
  },
  servicePublicadoChipNoDark: {
    backgroundColor: 'rgba(234, 179, 8, 0.2)',
    borderColor: '#FACC15',
  },
  servicePublicadoChipText: {
    fontSize: fontSizes.FONT10,
    fontFamily: appFonts.bold,
    fontWeight: '800',
  },
  servicePublicadoChipTextSi: {
    color: '#166534',
  },
  servicePublicadoChipTextSiDark: {
    color: '#86EFAC',
  },
  servicePublicadoChipTextNo: {
    color: '#854D0E',
  },
  servicePublicadoChipTextNoDark: {
    color: '#FDE68A',
  },
  tagChip: {
    maxWidth: '100%',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
  },
  tagChipCategory: {
    backgroundColor: '#EEF2FF',
    borderColor: '#2D3261',
  },
  tagChipCategoryDark: {
    backgroundColor: 'rgba(45, 50, 114, 0.45)',
    borderColor: '#94A3B8',
  },
  tagChipSub: {
    backgroundColor: '#FFFBF0',
    borderColor: '#1F2344',
  },
  tagChipSubDark: {
    backgroundColor: 'rgba(9, 13, 46, 0.35)',
    borderColor: '#5C6B8A',
  },
  tagChipText: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.semiBold,
    fontWeight: '600',
    lineHeight: 15,
  },
  tagChipTextCategory: {
    color: '#1F2344',
  },
  tagChipTextCategoryDark: {
    color: '#E2E8F0',
  },
  tagChipTextSub: {
    color: '#1F2344',
  },
  tagChipTextSubDark: {
    color: '#FEF3C7',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: windowWidth(3),
  },
  metaLabel: {
    width: windowWidth(26),
    minWidth: 92,
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.semiBold,
    fontWeight: '600',
    lineHeight: windowHeight(17),
    paddingTop: 1,
  },
  metaValue: {
    flex: 1,
    minWidth: 0,
    fontSize: fontSizes.FONT13,
    fontFamily: appFonts.Regular,
    fontWeight: '500',
    lineHeight: windowHeight(19),
  },
  metaValueBold: {
    fontFamily: appFonts.bold,
    fontWeight: '700',
  },
  publicadoWrap: {
    width: '100%',
    maxWidth: '100%',
    alignSelf: 'stretch',
    marginTop: 2,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1F2344',
    backgroundColor: '#EEF4FF',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 6,
    overflow: 'hidden',
  },
  publicadoWrapDark: {
    backgroundColor: 'rgba(9, 13, 46, 0.45)',
    borderColor: '#5C6B8A',
  },
  publicadoLeft: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
    alignItems: 'center',
    gap: 6,
  },
  publicadoTitleWrap: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
  },
  publicadoIconCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#1F2344',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFD60A',
    flexShrink: 0,
  },
  publicadoIconCircleDark: {
    backgroundColor: '#1F2344',
    borderColor: '#FFD60A',
  },
  publicadoTitle: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.semiBold,
    fontWeight: '600',
    lineHeight: windowHeight(16),
  },
  publicadoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    flexShrink: 0,
    maxWidth: '100%',
  },
  publicadoBadgeSi: {
    backgroundColor: '#DCFCE7',
    borderColor: '#22C55E',
  },
  publicadoBadgeNo: {
    backgroundColor: '#F1F5F9',
    borderColor: '#94A3B8',
  },
  publicadoBadgeSiDark: {
    backgroundColor: 'rgba(34, 197, 94, 0.22)',
    borderColor: '#4ADE80',
  },
  publicadoBadgeNoDark: {
    backgroundColor: 'rgba(148, 163, 184, 0.2)',
    borderColor: '#94A3B8',
  },
  publicadoBadgeText: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.bold,
    fontWeight: '700',
  },
  publicadoBadgeTextSi: {
    color: '#166534',
  },
  publicadoBadgeTextNo: {
    color: '#475569',
  },
  publicadoBadgeTextSiDark: {
    color: '#86EFAC',
  },
  publicadoBadgeTextNoDark: {
    color: '#E2E8F0',
  },
  ratingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBF0',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#1F2344',
  },
  ratingPillText: {
    marginLeft: 4,
    color: '#B45309',
    fontFamily: appFonts.bold,
    fontWeight: '700',
    fontSize: fontSizes.FONT14,
  },
  serviceFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E8ECF5',
  },
  serviceFooterCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 'auto',
    paddingTop: 12,
    width: '100%',
    gap: 8,
  },
  serviceModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(9, 13, 46, 0.52)',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  serviceModalCard: {
    zIndex: 2,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 20,
    shadowColor: '#1F2344',
    shadowOffset: {width: 0, height: 12},
    shadowOpacity: 0.22,
    shadowRadius: 24,
    elevation: 12,
    borderWidth: 1,
    borderColor: '#E8ECF5',
  },
  serviceModalCardDark: {
    backgroundColor: '#1E2235',
    borderColor: '#334155',
  },
  serviceModalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 8,
  },
  serviceModalTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  serviceModalTitle: {
    fontSize: fontSizes.FONT19,
    fontFamily: appFonts.bold,
    fontWeight: '800',
    lineHeight: 26,
  },
  serviceModalSubtitle: {
    marginTop: 4,
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.semiBold,
    fontWeight: '600',
    lineHeight: 17,
  },
  serviceModalCloseBtn: {
    padding: 4,
    marginTop: -2,
  },
  serviceModalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 10,
    gap: 12,
  },
  serviceModalOptionLast: {
    marginBottom: 0,
  },
  serviceModalOptionDark: {
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    borderColor: '#475569',
  },
  serviceModalIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#FFD60A',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E7BF00',
  },
  serviceModalIconWrapDark: {
    backgroundColor: '#CA8A04',
    borderColor: '#A16207',
  },
  serviceModalOptionText: {
    flex: 1,
    minWidth: 0,
  },
  serviceModalOptionTitle: {
    fontSize: fontSizes.FONT16,
    fontFamily: appFonts.bold,
    fontWeight: '800',
    marginBottom: 4,
  },
  serviceModalOptionDesc: {
    fontSize: fontSizes.FONT12,
    fontFamily: appFonts.semiBold,
    fontWeight: '500',
    lineHeight: 17,
  },
  serviceModalChevron: {
    flexShrink: 0,
  },
  verMasLink: {
    fontSize: fontSizes.FONT14,
    color: '#2D3261',
    fontWeight: '700',
    textDecorationLine: 'underline',
    fontFamily: appFonts.semiBold,
  },
  verMasRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  verMasMuted: {
    fontSize: fontSizes.FONT14,
    color: '#64748B',
    fontWeight: '600',
    fontFamily: appFonts.semiBold,
  },
  verMasArrow: {
    marginStart: 2,
  },
  pricePill: {
    backgroundColor: '#1F2344',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2D3261',
  },
  pricePillText: {
    fontSize: fontSizes.FONT18,
    color: '#FFD60A',
    fontFamily: appFonts.semiBold,
    fontWeight: '800',
  },
  pricePillYellow: {
    flexShrink: 0,
    backgroundColor: '#FFD60A',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E7BF00',
  },
  pricePillYellowText: {
    fontSize: fontSizes.FONT16,
    color: '#1F2344',
    fontFamily: appFonts.bold,
    fontWeight: '800',
  },
});

export default styles;
