import {StyleSheet} from 'react-native';
import appFonts from '../../../themes/appFonts';
import {external} from '../../../style/external.css';
import {commonStyles} from '../../../style/commonStyle.css';
import appColors from '../../../themes/appColors';
import {
  fontSizes,
  windowHeight,
  windowWidth,
} from '../../../themes/appConstant';
const styles = StyleSheet.create({
  topNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    backgroundColor: '#1F2344',
    // position: 'relative',
    // overflow: 'hidden',
    // zIndex: 20,
    elevation: 8,
    height: 60,
    padding: 10,
  },
  topNavLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 30,
  },
  topNavBackBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,214,10,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topNavTitle: {
    marginLeft: 10,
    color: '#FFEA00',
    fontSize: 20,
    fontWeight: '900',
  },
  topNavSpacer: {
    width: 34,
    height: 34,
  },
  topNavCircle1: {
    position: 'absolute',
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(255,214,10,0.12)',
    top: -20,
    right: -12,
  },
  topNavCircle2: {
    position: 'absolute',
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255,255,255,0.10)',
    bottom: -14,
    left: -8,
  },
  mainCard: {
    marginTop: 12,
    backgroundColor: '#F8FAFF',
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: '#D7E4FF',
    shadowColor: '#1F2344',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  serviceHeaderChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFD60A',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 8,
  },
  serviceHeaderChipText: {
    color: '#1F2344',
    fontSize: 11,
    fontWeight: '800',
  },
  serviceTitle: {
    color: '#1F2344',
    fontSize: 24,
    fontWeight: '900',
    marginTop: 2,
  },
  serviceMetaRow: {
    marginTop: 6,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  serviceMetaText: {
    color: '#1F2344',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 28,
    flex: 1,
    marginRight: 10,
  },
  priceInlineRow: {
    marginTop: 0,
    marginBottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#FFF8E6',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#F8D774',
  },
  priceInlineLabel: {
    color: '#6F5C00',
    fontSize: 13,
    fontWeight: '700',
    marginRight: 6,
  },
  priceInlineValue: {
    color: '#1F2344',
    fontSize: 20,
    fontWeight: '900',
  },
  descriptionCard: {
    marginTop: 4,
    marginBottom: 8,
    backgroundColor: '#EEF4FF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#CFE0FF',
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  infoBlockCard: {
    marginTop: 6,
    marginBottom: 8,
    backgroundColor: '#EEF4FF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#CFE0FF',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  infoBlockTitle: {
    color: '#1F2344',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 6,
  },
  infoBlockText: {
    color: '#2A305E',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  horarioSectionWrap: {
    marginTop: 8,
    marginBottom: 4,
    backgroundColor: '#EEF4FF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#CFE0FF',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  horarioSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 8,
  },
  horarioSectionTitle: {
    color: '#1F2344',
    fontSize: 16,
    fontWeight: '800',
  },
  horarioSectionPlain: {
    color: '#2A305E',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '500',
  },
  horarioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(31, 35, 68, 0.08)',
  },
  horarioDayLabel: {
    color: '#1F2344',
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
    marginRight: 8,
  },
  horarioTimeText: {
    color: '#2A305E',
    fontSize: 14,
    fontWeight: '600',
  },
  paymentSectionWrap: {
    marginTop: 4,
    backgroundColor: '#1F2344',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingBottom: 10,
    marginBottom: 10,
    marginTop: 20,
  },
  ratingPill: {
    backgroundColor: '#FFD60A',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 66,
  },
  ratingPillText: {
    color: '#6F5C00',
    fontSize: 13,
    fontWeight: '800',
  },
  ratingPillRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingPillArrow: {
    color: '#6F5C00',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 16,
  },
  estadoPill: {
    backgroundColor: '#1F2344',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  estadoPillText: {
    color: '#FFD60A',
    fontSize: 11,
    fontWeight: '700',
  },
  mapOpenButton: {
    borderWidth: 1,
    borderColor: '#2D3261',
    borderRadius: 10,
    backgroundColor: '#252b4a',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    width: windowWidth(350),
  },
  mapOpenButtonText: {
    color: '#E8EAFF',
    fontWeight: '800',
  },
  similaresTitleWrap: {
    backgroundColor: '#1F2344',
    borderRadius: 14,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#2D3261',
  },
  similaresSectionTitle: {
    fontSize: 21,
    fontWeight: '700',
    color: '#FFD60A',
    letterSpacing: 0.3,
  },
  similaresRow: {
    paddingRight: 6,
  },
  similarServiceCard: {
    width: 265,
    backgroundColor: '#F6F2F6',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 8,
  },
  similarServiceImage: {
    width: '100%',
    height: 130,
    backgroundColor: '#E5E7EB',
  },
  similarServiceBody: {
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  similarServiceTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1F2344',
    marginBottom: 3,
  },
  similarMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
    flexWrap: 'wrap',
  },
  similarMetaChip: {
    backgroundColor: '#2D3261',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginRight: 6,
    marginBottom: 4,
    maxWidth: '72%',
  },
  similarMetaChipText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#E8EAFF',
  },
  similarScoreChip: {
    backgroundColor: '#FFF4CC',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginBottom: 4,
  },
  similarScoreChipText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#7A5A00',
  },
  similarServicePrice: {
    fontSize: 12,
    color: '#15803D',
    fontWeight: '800',
    marginBottom: 4,
  },
  similarServiceDesc: {
    fontSize: 12,
    color: '#4B5563',
    lineHeight: 17,
  },
  similarDetailBtn: {
    marginTop: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#FFD60A',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  similarDetailBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#1F2344',
  },
  similaresEmpty: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  similaresEmptyText: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
  },
  heroInfoOverlay: {
    marginTop: -96,
    backgroundColor: 'rgba(31,35,68,0.88)',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    zIndex: 5,
  },
  heroTopBadges: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  heroBadgeActive: {
    backgroundColor: '#FFD60A',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  heroBadgeActiveText: {
    color: '#6F5C00',
    fontSize: 10,
    fontWeight: '800',
  },
  heroBadgeEstado: {
    marginLeft: 8,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  heroBadgeEstadoText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  heroServiceTitle: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 34,
  },
  heroServiceSubtitle: {
    marginTop: 4,
    color: 'rgba(255,255,255,0.9)',
    fontSize: 13,
    fontWeight: '600',
  },
  hero: {
    marginHorizontal: 14,
    borderRadius: 24,
    overflow: 'hidden',
    height: 340,
    backgroundColor: '#1F2344',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(9,13,46,0.30)',
  },
  heroBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 18,
    paddingBottom: 50,
    paddingTop: 20,
    backgroundColor: 'rgba(9,13,46,0.62)',
  },
  heroBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 7,
  },
  activeBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFD60A',
    color: '#6F5C00',
    borderRadius: 999,
    paddingVertical: 3,
    paddingHorizontal: 10,
    fontSize: 10,
    fontWeight: '800',
  },
  estadoBadge: {
    marginLeft: 8,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.18)',
    color: '#FFFFFF',
    borderRadius: 999,
    paddingVertical: 3,
    paddingHorizontal: 10,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  heroName: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '900',
  },
  heroTallerBadge: {
    marginTop: 8,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 999,
    paddingVertical: 6,
    paddingLeft: 12,
    paddingRight: 8,
    maxWidth: '96%',
    borderWidth: 1,
    borderColor: 'rgba(255,214,10,0.55)',
    gap: 4,
  },
  heroTallerBadgeDisabled: {
    opacity: 0.65,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  heroTallerBadgeText: {
    flexShrink: 1,
    minWidth: 0,
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  heroTallerBadgeChevron: {
    flexShrink: 0,
    marginStart: 2,
  },
  heroRif: {
    marginTop: 3,
    color: 'rgba(255,255,255,0.88)',
    fontSize: 13,
    fontWeight: '600',
  },
  actionsRow: {
    marginTop: -35,
    marginHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    zIndex: 4,
  },
  actionBtn: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  actionYellow: {
    backgroundColor: '#FFD60A',
  },
  actionGreen: {
    backgroundColor: '#22A55A',
  },
  actionBlue: {
    backgroundColor: '#2D3261',
  },
  actionWhiteText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  actionYellowText: {
    color: '#6F5C00',
    fontSize: 12,
    fontWeight: '800',
  },
  listItem: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    padding: 10,
    marginVertical: 5,
    backgroundColor: '#fff',
    borderRadius: 10,
    elevation: 2, // Para sombreado en Android
  },
  button: {
    padding: 10,
    marginVertical: 5,
    backgroundColor: '#1F2344',
    borderRadius: 5,
    alignItems: 'center',
  },
  text: {
    color: '#fff',
    fontWeight: 'bold',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5, // Sombra en Android
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Si necesitas un fondo tenue
  },
  listItem: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    padding: 15,
    marginVertical: 5,
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    elevation: 1,
  },
  button: {
    padding: 10,
    backgroundColor: '#1F2344',
    borderRadius: 5,
    alignItems: 'center',
    marginVertical: 5,
  },
  text: {
    color: '#000',
    fontWeight: 'bold',
  },
  buttonClose: {
    backgroundColor: '#f44336',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  
  phone: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    flex: 1,
    marginLeft: 10,
  },
  container: {
    padding: 10,
    marginTop: 20,
    backgroundColor: '#1F2344',
    borderRadius: 10,
    alignItems: 'center',
  },
  welcome: {
    color: '#fff', // Contraste con el fondo
    fontSize: 16,
    fontWeight: 'bold',
  },
  
  icon: {
    marginLeft: 10,
  },
  copyIcon: {
    marginRight: 10,
  },
  button: {
    marginTop: 20,
    borderRadius: 5,
    padding: 10,
    elevation: 2,
    width: '80%',
  },
  buttonClose: {
    backgroundColor: '#1F2344',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  textContext: {
    ...commonStyles.H1Banner,
    fontSize: fontSizes.FONT30,
    color: appColors.titleText,
    fontFamily: appFonts.semiBold,
    textAlign: 'center',
    marginTop: windowHeight(9),
  },
  progressBar: {
    width: windowWidth(205),
    backgroundColor: '#E8EAEE',
    height: windowHeight(3),
    borderRadius: windowHeight(4),
    ...external.ai_center,
    ...external.mh_5,
  },
  progressBarPrimary: {
    backgroundColor: appColors.primary,
    height: windowHeight(3),
    borderRadius: windowHeight(4),
    ...external.ai_center,
    position: 'absolute',
    alignSelf: 'flex-start',
    width: windowWidth(150),
  },
  buyNowText: {
    ...commonStyles.titleText19,
    color: '#FFD60A',
    fontSize: fontSizes.FONT21,
    paddingHorizontal: windowHeight(3),
  },
  contactFooterButton: {
    width: windowWidth(320),
    alignSelf: 'center',
    backgroundColor: '#FFD60A',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E7BF00',
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactFooterIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(31,35,68,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  contactFooterButtonText: {
    color: '#1F2344',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  addToBeg: {
    ...commonStyles.H1Banner,
    fontSize: fontSizes.FONT21,
    color: '#1F2344',
  },
  bottomContainerView: {
    flex: 1,
    justifyContent: 'flex-end',
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#1F2344',
  },
  footerValueDarkContainer: {
    backgroundColor: '#1F2344',
    width: windowWidth(260),
    borderTopLeftRadius: windowHeight(37),
  },
  footerActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  footerActionText: {
    color: '#FFD60A',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  footerLeftText: {
    ...commonStyles.H1Banner,
    fontSize: fontSizes.FONT21,
    color: '#FFD60A',
  },
  priceContainer: {
    fontSize: fontSizes.FONT30,
    color: appColors.titleText,
    fontFamily: appFonts.semiBold,
    lineHeight: 30,
  },
  percentageOff: {
    backgroundColor: '#FDDBDB',
    width: windowWidth(90),
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshIcon: {
    ...external.fd_row,
    ...external.ai_center,
    ...external.js_space,
    borderWidth: 1,
    borderColor: appColors.bgLayer,
    borderRadius: windowHeight(8),
    marginTop: windowHeight(10),
    paddingVertical: windowHeight(13),
    paddingHorizontal: windowWidth(10),
    elevation: 0.5,
    backgroundColor: appColors.screenBg,
  },
  verticalLine: {
    height: '70%',
    width: 2,
    backgroundColor: appColors.subtitle,
  },
  deliveryIn: {
    ...commonStyles.titleText19,
    width: windowWidth(105),
    fontSize: fontSizes.FONT17,
    marginHorizontal: windowHeight(8),
    lineHeight: windowHeight(17),
  },
  minus: {
    borderWidth: 1,
    width: windowWidth(165),
    borderColor: appColors.cardBorder,
    borderRadius: windowHeight(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    height: windowHeight(34),
    elevation: 1,
    backgroundColor: appColors.screenBg,
  },
  priceText: {
    ...commonStyles.subtitleText,
    textDecorationLine: 'line-through',
  },
  viewContainer: {
    backgroundColor: '#2D3261',
    borderRadius: windowHeight(8),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: windowHeight(8),
    marginHorizontal: windowHeight(3),
    width: windowWidth(78),
    height: windowHeight(48),
  },
  writeYourReview: {
    ...commonStyles.titleText19,
    ...external.ph_20,
    ...external.mt_5,
    color: '#2D3261',
    fontSize: fontSizes.FONT17,
  },
  outOfFive: {
    ...commonStyles.subtitleText,
    color: appColors.screenBg,
    lineHeight: 15,
    top: windowHeight(3),
  },
  fourPointOne: {
    ...commonStyles.titleText19,
    color: appColors.screenBg,
    fontFamily: appFonts.semiBold,
    lineHeight: windowHeight(17),
  },
  upTofive: {
    ...commonStyles.titleText19,
    width: windowWidth(105),
    fontSize: fontSizes.FONT17,
    marginHorizontal: 10,
    lineHeight: windowHeight(17),
  },
  titleView: {
    ...commonStyles.subtitleText,
    width: 75,
    color: appColors.titleText,
  },
  ratingScreen: {
    ...external.fd_row,
    ...external.ai_center,
    ...external.mh_10,
    marginVertical: 3,
  },
});

export default styles;
