import {StyleSheet} from 'react-native';
import {windowHeight, windowWidth} from '../../../../themes/appConstant';
import appColors from '../../../../themes/appColors';

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.52)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: windowWidth(10),
    paddingVertical: windowHeight(3),
  },
  card: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: windowWidth(7),
    paddingTop: windowHeight(2.5),
    paddingBottom: windowHeight(2),
    maxHeight: '90%',
    minHeight: '65%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: windowHeight(2.2),
    marginHorizontal: -windowWidth(7),
    marginTop: -windowHeight(2.5),
    paddingVertical: 16,
    paddingHorizontal: windowWidth(7),
    paddingBottom: 18,
    paddingTop: 14,
    backgroundColor: appColors.primary ?? '#2D3261',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    position: 'relative',
  },
  headerTitleWrap: {
    flex: 1,
    paddingRight: 12,
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  headerSubtitle: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.9)',
    marginTop: 6,
    lineHeight: 18,
  },
  closeBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    padding: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  scrollContent: {
    paddingBottom: windowHeight(2.5),
    paddingTop: 4,
  },
  field: {
    marginBottom: windowHeight(2.2),
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  labelRequired: {
    color: '#E53935',
  },
  fieldHint: {
    fontSize: 12,
    color: '#9CA3AF',
    marginBottom: 10,
    lineHeight: 17,
  },
  input: {
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 13,
    fontSize: 15,
    backgroundColor: '#FAFAFA',
  },
  dropdown: {
    width: '100%',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 16,
    backgroundColor: '#FAFAFA',
    height: 52,
  },
  dropdownPlaceholder: {
    color: '#9CA3AF',
    fontSize: 15,
  },
  dropdownSelectedText: {
    color: '#374151',
    fontSize: 15,
  },
  dateInputTouchable: {
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 13,
    backgroundColor: '#FAFAFA',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateInputText: {
    fontSize: 15,
    color: '#374151',
  },
  dateInputPlaceholder: {
    color: '#9CA3AF',
  },
  imagePickTouchable: {
    width: '100%',
    minHeight: 168,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    backgroundColor: '#F9FAFB',
  },
  imagePlaceholder: {
    flex: 1,
    minHeight: 168,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    paddingHorizontal: 20,
  },
  imagePlaceholderText: {
    fontSize: 14,
    color: '#9CA3AF',
    marginTop: 12,
  },
  imagePreviewWrap: {
    width: '100%',
    minHeight: 168,
    position: 'relative',
  },
  imagePreview: {
    width: '100%',
    height: 200,
    backgroundColor: '#E5E7EB',
  },
  imageRemoveBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 16,
  },
  datePicker: {
    height: 150,
  },
  datePickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  datePickerBox: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 20,
    alignItems: 'center',
  },
  datePickerTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: appColors.primary,
    marginBottom: 12,
  },
  datePickerFooter: {
    flexDirection: 'row',
    marginTop: 14,
  },
  datePickerBtnCancel: {
    flex: 1,
    marginRight: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#E8ECF4',
    alignItems: 'center',
  },
  datePickerBtnCancelText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
  },
  datePickerBtnConfirm: {
    flex: 1,
    marginLeft: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: appColors.primary,
    alignItems: 'center',
  },
  datePickerBtnConfirmText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  row: {
    flexDirection: 'row',
  },
  rowHalf: {
    flex: 1,
    marginHorizontal: 6,
  },
  footer: {
    flexDirection: 'row',
    marginTop: windowHeight(2.5),
    paddingTop: 18,
    borderTopWidth: 2,
    borderTopColor: '#EEF2F7',
  },
  btn: {
    flex: 1,
    marginHorizontal: 6,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnSecondary: {
    backgroundColor: '#F3F4F6',
  },
  btnPrimary: {
    backgroundColor: appColors.primary ?? '#2D3261',
  },
  btnDisabled: {
    opacity: 0.7,
  },
  btnTextSecondary: {
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
  },
  btnTextPrimary: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: windowHeight(2.2),
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  switchLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    flex: 1,
  },
  stepSection: {
    marginBottom: windowHeight(3),
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 0,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: appColors.primaryLight ?? '#E8ECFF',
    borderRadius: 14,
  },
  stepHeaderExpanded: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  stepHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  stepBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: appColors.primary ?? '#2D3261',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  stepBadgeText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: appColors.primary ?? '#2D3261',
  },
  stepCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 0,
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
    padding: 18,
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: '#E8ECF4',
  },
});

export default styles;
