import {StyleSheet} from 'react-native';
import {fontSizes, windowHeight, windowWidth} from '../../themes/appConstant';
import appColors from '../../themes/appColors';
import {commonStyles} from '../../style/commonStyle.css';
import {external} from '../../style/external.css';
const styles = StyleSheet.create({
  headingContainer: {
    ...commonStyles.titleText19,
  },
  container: {
    flex: 1,
    backgroundColor: '#F3F6FB',
    paddingHorizontal: windowWidth(16),
  },
  modalScrollContent: {
    paddingBottom: 150,
  },
  modalBodyTop: {
    marginTop: 54,
  },
  modalHeroCard: {
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: windowWidth(16),
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#31407A',
    position: 'relative',
    marginHorizontal: 0,
    minHeight: 145,
    overflow: 'hidden',
  },
  modalHeroTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  modalHeroEyebrow: {
    fontSize: 12,
    color: '#FFD60A',
    fontWeight: '800',
    marginBottom: 0,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  modalHeroTitle: {
    fontSize: 21,
    color: '#FFFFFF',
    fontWeight: '900',
    marginBottom: 8,
    lineHeight: 28,
    paddingRight: 8,
  },
  modalHeroSubtitle: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.9)',
    lineHeight: 20,
    paddingRight: 8,
  },
  modalHeroTypeBadge: {
    backgroundColor: 'rgba(17, 24, 39, 0.45)',
    borderRadius: 999,
    borderWidth: 0,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  modalHeroTypeBadgeText: {
    color: '#FFD60A',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  modalUploadCard: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D9E3F2',
    backgroundColor: '#F8FBFF',
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  uploadPreviewImage: {
    width: 210,
    height: 210,
    borderRadius: 10,
  },
  uploadButton: {
    borderWidth: 1.5,
    borderColor: '#2D3261',
    borderStyle: 'dashed',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 12,
  },
  uploadButtonText: {
    marginLeft: 10,
    color: '#2D3261',
    fontWeight: '800',
    fontSize: 14,
  },
  uploadHelperText: {
    marginTop: 8,
    color: '#64748B',
    fontSize: 12,
    textAlign: 'center',
  },
  efectivoInputsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  efectivoInputCol: {
    width: '48.5%',
  },
  dateInputTrigger: {
    marginTop: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    minHeight: 52,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  dateInputText: {
    color: '#1F2344',
    fontSize: 15,
    fontWeight: '700',
  },
  modalFixedFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: windowWidth(16),
    paddingTop: 10,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  modalFixedFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalActionBtn: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  modalActionBtnReport: {
    backgroundColor: '#FFD60A',
    marginLeft: 8,
  },
  modalActionBtnCancel: {
    backgroundColor: '#E2E8F0',
    marginRight: 8,
  },
  modalActionBtnText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1F2344',
  },
  modalActionBtnIconSpacing: {
    marginRight: 6,
  },
  viewContainer: {
    marginTop: 15,
    borderRadius: 10,
    borderColor: appColors.solideLine,
    backgroundColor: appColors.screenBg,
    padding: 1,
    overflow: 'hidden',
    elevation: 2,
  },
  payNowText: {
    ...commonStyles.titleText19,
    color: '#1F2344',
    fontSize: fontSizes.FONT21,
    paddingHorizontal: 6,
    fontWeight: '800',
  },
  footerLeftContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    marginLeft: 10,
  },
  footerTotalText: {
    color: '#1F2344',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 2,
  },
  priceText: {
    ...commonStyles.H1Banner,
    fontSize: fontSizes.FONT33 || 34,
    color: '#1F2344',
    paddingHorizontal: windowHeight(14),
    fontWeight: '900',
    lineHeight: 34,
  },
  footerPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  footerAmountText: {
    fontSize: fontSizes.FONT33 || 34,
    fontWeight: 'bold',
    color: '#1F2344',
    lineHeight: 34,

  },
  footerPlanBadge: {
    marginLeft: 8,
    backgroundColor: '#1F2344',
    borderColor: 'transparent',
    borderWidth: 0,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  footerPlanBadgeText: {
    color: '#FFD60A',
    fontSize: 10,
    fontWeight: '800',
  },
  footerValueContainer: {
    backgroundColor: '#FFD60A',
    borderRadius: 999,
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    height: windowHeight(40),
    marginTop: 20,
  },
  footerReportButton: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    height: windowHeight(20),
    paddingHorizontal: 0,
    
  },
  titleBooks: {
    ...commonStyles.subtitleText,
    ...external.ph_10,
    fontSize: fontSizes.FONT18,
    color: appColors.titleText,
    flexGrow: 0.96,
  },
  otherPaymentModeText: {
    backgroundColor: appColors.screenBg,
    marginVertical: 10,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 1,
    overflow: 'hidden',
    elevation: 2,
  },
  imgContainer: {
    width: 35,
    height: 35,
    resizeMode: 'contain',
  },
  imgGround: {
    width: 34,
    height: 27,
    resizeMode: 'contain',
  },
  addnewCard: {
    ...commonStyles.titleText19,
    ...external.mh_15,
    ...external.mt_10,
    color: '#2D3261',
    fontSize: fontSizes.FONT19,
    textDecorationLine: 'underline',
  },
  imgStyle: {
    width: windowWidth(310),
    height: windowHeight(200),
    alignSelf: 'center',
  },
  succesfullImg: {
    width: windowWidth(310),
    height: windowHeight(200),
    alignSelf: 'center',
  },
  menuItemContent: {
    borderRadius: 6,
    width: '100%',
  },
  menuItemContentTwo: {
    borderRadius: 10,
    width: '100%',
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignItems: 'center',
  },
  // ===== Tarjetas métodos de pago (diseño tipo HTML) =====
  paymentCard: {
    borderRadius: 22,
    overflow: 'hidden',
    padding: 22,
    paddingBottom: 0,
    marginBottom: 0,
    position: 'relative',
  },
  paymentCardSelected: {
    // El borde amarillo se dibuja como overlay interno en el contenedor azul.
  },
  paymentCardSelectedOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 22,
    // borderWidth: 3,
    borderColor: '#FFD60A',
    pointerEvents: 'none',
  },
  paymentCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingRight: 32,
    
  },
  paymentHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  paymentIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  paymentIconCash: {
    backgroundColor: '#FFD60A',
  },
  paymentIconDefault: {
    backgroundColor: '#FFD60A',
  },
  paymentTitles: {
    fontWeight: '800',
    fontSize: 18,
    color: '#FFFFFF',
  },
  paymentSubtitle: {
    color: '#1F2344',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    alignSelf: 'flex-start',
  },
  radioOuter: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 0,
    marginTop: 0,
  },
  radioOuterSelected: {
    borderColor: '#FFD60A',
  },
  radioInnerDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#FFD60A',
  },
  radioInnerDotHidden: {
    opacity: 0,
  },
  radioInnerDotVisible: {
    opacity: 1,
  },
  paymentDetailsWrap: {
    marginTop: 18,
    marginHorizontal: -22,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingTop: 16,
    paddingHorizontal: 22,
    paddingBottom: 28,
    width: '100%',
  },
  detailsGridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  detailsCol: {
    flex: 1,
    minWidth: 0,
    paddingRight: 10,
  },
  detailsColNoPad: {
    flex: 1,
    paddingRight: 0,
  },
  detailsLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: '#2D3261',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  detailsValue: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  detailsValueSmall: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#1F2344',
    flexShrink: 1,
    flexWrap: 'wrap',
  },
});

export {styles};
