import {StyleSheet} from 'react-native';
import {external} from '../../style/external.css';
import {
  fontSizes,
  windowHeight,
  windowWidth,
} from '../../themes/appConstant';
import {commonStyles} from '../../style/commonStyle.css';


const styles = StyleSheet.create({
  headingContainer: {
    ...commonStyles.titleText19,
  },
  container: {
    ...external.fd_row,
    ...external.pt_10,
    ...external.as_center,
  },
  flexView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: windowHeight(14),
  },
  imgStyle1: {
    width: windowWidth(330),
    height: windowHeight(220),
    alignSelf: 'center',
  },
  bagIsEmptyText: {
    ...commonStyles.titleText19,
    ...external.ti_center,
    fontSize: fontSizes.FONT23,
  },
  bagisEmptySomething: {
    ...commonStyles.subtitleText,
    ...external.ti_center,
    ...external.mt_3,
    ...external.mb_20,
    fontSize: fontSizes.FONT19,
    marginTop:20
  },
  imgStyle: {
    width: windowWidth(90),
    height: windowHeight(54),
    marginTop: windowHeight(24),
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  editIconStyle: {
    backgroundColor: '#F3F5FB',
    width: windowHeight(24),
    height: windowHeight(24),
    borderRadius: windowHeight(24),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    top: '55%',
  },
  loadingContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 100,
    minHeight: 100,
  },
  /** Header alineado con Servicios / Vehículos */
  formHeaderWrapper: {
    width: '100%',
    backgroundColor: '#1F2344',
    paddingBottom: windowHeight(4.6),
    paddingHorizontal: windowWidth(5),
    justifyContent: 'center',
    overflow: 'hidden',
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    borderBottomWidth: 7,
    borderBottomColor: '#FFD60A',
    position: 'relative',
  },
  formHeaderCircle1: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(255,214,10,0.12)',
    top: -34,
    right: -22,
  },
  formHeaderCircle2: {
    position: 'absolute',
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(255,255,255,0.10)',
    top: 30,
    left: -14,
  },
  formHeaderBackBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255,214,10,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    left: windowWidth(4),
    zIndex: 3,
    top: 0,
  },
  formHeaderTitle: {
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '900',
    color: '#FFD60A',
    marginTop: windowHeight(10),
    marginBottom: 6,
    paddingHorizontal: 48,
  },
  formHeaderSubtitle: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    opacity: 0.95,
    lineHeight: 20,
    paddingHorizontal: 8,
  },
  /** Galería: bloque claro (sin fondo azul oscuro) */
  formPhotoHeroOuter: {
    marginTop: 10,
    marginBottom: 20,
  },
  formPhotoHero: {
    width: '95%',
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8ECF5',
    paddingTop: windowHeight(12),
    paddingBottom: windowHeight(20),
    paddingHorizontal: 14,
    overflow: 'hidden',
    shadowColor: '#1F2344',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  formPhotoHeroTitle: {
    fontSize: fontSizes.FONT20,
    fontWeight: '800',
    color: '#1F2344',
    marginBottom: 6,
  },
  formPhotoHeroHint: {
    fontSize: fontSizes.FONT12,
    color: '#64748B',
    marginBottom: 14,
    lineHeight: 18,
    paddingHorizontal: 8,
  },
  formPhotoStripWrap: {
    width: '100%',
    minHeight: 168,
  },
  formPhotoStrip: {
    width: '100%',
  },
  formPhotoStripContent: {
    alignItems: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 8,
    gap: 10,
  },
  formPhotoLoadingBox: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F3F5FB',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8ECF5',
  },
  formPhotoLoadingText: {
    marginTop: 12,
    color: '#64748B',
    fontSize: fontSizes.FONT14,
    fontWeight: '600',
  },
  formPhotoPlaceholderSlide: {
    flex: 1,
    marginHorizontal: 4,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#DDE2E8',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    paddingHorizontal: 20,
    minHeight: 200,
  },
  formPhotoPlaceholderLogo: {
    width: 72,
    height: 72,
    marginBottom: 12,
    opacity: 0.95,
  },
  formPhotoPlaceholderIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FFD60A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  formPhotoPlaceholderTitle: {
    fontSize: fontSizes.FONT17,
    fontWeight: '800',
    color: '#1F2344',
    marginBottom: 6,
    textAlign: 'center',
  },
  formPhotoPlaceholderSub: {
    fontSize: fontSizes.FONT13,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 20,
  },
  formPhotoCell: {
    width: 118,
    position: 'relative',
  },
  formPhotoCellImage: {
    width: 118,
    height: 148,
    borderRadius: 12,
    backgroundColor: '#E8ECF5',
  },
  formPhotoCellRemove: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(9,13,46,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFD60A',
  },
  formPhotoCellBadge: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    right: 4,
    backgroundColor: 'rgba(9,13,46,0.85)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,214,10,0.5)',
    alignSelf: 'center',
  },
  formPhotoCellBadgeText: {
    color: '#FFD60A',
    fontSize: fontSizes.FONT10,
    fontWeight: '700',
    textAlign: 'center',
  },
  formPhotoFormCard: {
    marginTop: -30,
    marginHorizontal: 0,
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    paddingVertical: 4,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: '#E8ECF5',
    width: '85%',
    alignSelf: 'center',
  },
  formPhotoAddBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 4,
    gap: 12,
  },
  formPhotoAddBarIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#FFFBF0',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFE6A8',
  },
  formPhotoAddBarTitle: {
    fontSize: fontSizes.FONT15,
    fontWeight: '700',
    color: '#1F2344',
  },
  formPhotoAddBarSub: {
    fontSize: fontSizes.FONT12,
    color: '#64748B',
    marginTop: 2,
  },
  formRowDropdowns: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
    marginBottom: 4,
    width: '100%',
  },
  formRowDropdownsInCard: {
    marginTop: 0,
    marginBottom: 12,
  },
  formDropdownCol: {
    flex: 1,
    minWidth: 0,
  },
  formDropdownLabel: {
    fontSize: fontSizes.FONT13,
    fontWeight: '600',
    marginBottom: 8,
  },
  formDropdownBox: {
    borderWidth: 1,
    borderColor: '#DDE2E8',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  formFooter: {
    borderTopWidth: 1,
    borderTopColor: '#E8ECF5',
    paddingHorizontal: windowWidth(5),
    paddingTop: 12,
    shadowColor: '#1F2344',
    shadowOffset: {width: 0, height: -3},
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 12,
  },
  formFooterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1F2344',
    borderRadius: 14,
    paddingVertical: 15,
    gap: 10,
    borderWidth: 1,
    borderColor: '#FFD60A',
  },
  formFooterBtnText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: fontSizes.FONT16,
  },
  /** Misma tarjeta que “Agregar fotos” (#F8FAFC + borde) */
  formServiceFieldsCard: {
    marginTop: 10,
    marginBottom: 4,
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: '#E8ECF5',
  },
  formRadioBlock: {
    marginTop: 8,
    marginBottom: 8,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#F3F5FB',
    borderWidth: 1,
    borderColor: '#E8ECF5',
  },
  formRadioBlockInCard: {
    marginTop: 4,
    marginBottom: 0,
    backgroundColor: '#FFFFFF',
    borderColor: '#E8ECF5',
  },
  formPublishWrap: {
    paddingVertical: 16,
    paddingHorizontal: 4,
  },
  formPublishHeader: {
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 16,
  },
  formPublishIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFBF0',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFE6A8',
  },
  formPublishHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  formPublishTitle: {
    fontSize: fontSizes.FONT16,
    fontWeight: '800',
    color: '#1F2344',
    marginBottom: 4,
    lineHeight: 22,
  },
  formPublishHint: {
    fontSize: fontSizes.FONT12,
    color: '#64748B',
    lineHeight: 18,
  },
  formPublishChipsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
  },
  formPublishChip: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E8ECF5',
    backgroundColor: '#F8FAFC',
    gap: 6,
  },
  formPublishChipSelected: {
    borderColor: '#FFD60A',
    backgroundColor: '#FFFBF0',
    borderWidth: 2,
  },
  formPublishChipTextCol: {
    flex: 1,
    minWidth: 0,
  },
  formPublishChipTitle: {
    fontSize: fontSizes.FONT14,
    fontWeight: '700',
  },
  formPublishChipSub: {
    fontSize: fontSizes.FONT11,
    color: '#64748B',
    marginTop: 2,
  },
});

export default styles;

