import { StyleSheet } from 'react-native';
import appColors from '../../themes/appColors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F6F8',
  },
  header: {
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 12,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: appColors.primary,
  },
  headerRefreshBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#F3F4F6',
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRefreshText: {
    fontSize: 11,
    fontWeight: '600',
    color: appColors.subtitle,
    marginLeft: 4,
    textTransform: 'uppercase',
  },
  headerSubtitle: {
    fontSize: 13,
    color: appColors.subtitle,
  },
  topHalf: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
  },
  topHalfTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: appColors.primary,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  enEsperaCard: {
    backgroundColor: '#FFF8E6',
    borderRadius: 14,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#FFD60A',
    minHeight: 0,
  },
  enEsperaHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  cancelTopBtn: {
    marginLeft: 6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: '#FEE2E2',
  },
  cancelTopBtnText: {
    marginLeft: 4,
    fontSize: 11,
    fontWeight: '600',
    color: '#B91C1C',
  },
  enEsperaEmpty: {
    backgroundColor: '#F9FAFB',
    borderRadius: 14,
    padding: 14,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 72,
  },
  enEsperaEmptyText: {
    fontSize: 12,
    color: appColors.subtitle,
    textAlign: 'center',
  },
  enEsperaBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    marginBottom: 4,
  },
  enEsperaBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#B45309',
    textTransform: 'uppercase',
  },
  enEsperaFotosScroll: {
    marginTop: 4,
    marginBottom: 4,
    marginHorizontal: -4,
  },
  enEsperaFotosContent: {
    paddingHorizontal: 4,
  },
  enEsperaFoto: {
    width: 72,
    height: 72,
    borderRadius: 10,
    backgroundColor: '#E5E7EB',
    marginRight: 8,
  },
  enEsperaServiceName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1F2933',
    marginBottom: 2,
  },
  enEsperaMetaText: {
    fontSize: 11,
    color: appColors.subtitle,
    marginTop: 2,
  },
  enEsperaVehicleText: {
    fontSize: 12,
    color: '#111827',
    marginTop: 2,
  },
  enEsperaDescText: {
    fontSize: 11,
    color: '#4B5563',
    marginTop: 4,
  },
  bottomHalf: {
    flex: 1,
    backgroundColor: '#F5F6F8',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 12,
    overflow: 'hidden',
  },
  tabsRowScroll: {
    flexGrow: 0,
    width: '100%',
  },
  tabsRowContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    paddingRight: 16,
    gap: 8,
  },
  tabChip: {
    flexShrink: 0,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabChipActive: {
    backgroundColor: '#FFD60A',
    borderColor: '#FFD60A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  tabChipLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: appColors.subtitle,
  },
  tabChipLabelActive: {
    color: appColors.primary,
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 24,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    marginTop: 10,
    marginHorizontal: 2,
    borderLeftWidth: 4,
    borderLeftColor: appColors.primary,
    shadowColor: appColors.shadowColor || '#202228',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    overflow: 'hidden',
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardInspeccionBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#FFFBEB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.35)',
  },
  cardInspeccionBannerIcon: {
    marginRight: 10,
    marginTop: 2,
  },
  cardInspeccionBannerText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: '#92400E',
    lineHeight: 19,
  },
  cardInspeccionBannerName: {
    fontWeight: '800',
    color: '#78350F',
  },
  cardStatusPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
  },
  cardTiempoEstimadoCaja: {
    backgroundColor: '#E5E7EB',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  cardTiempoEstimado: {
    fontSize: 11,
    fontWeight: '700',
    color: appColors.subtitle,
  },
  cardStatusPillText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  cardInfoBlock: {
    marginTop: 0,
  },
  cardInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: appColors.bgLayout || 'rgba(45, 50, 97, 0.06)',
    borderRadius: 10,
    marginBottom: 6,
  },
  cardInfoIcon: {
    marginRight: 8,
  },
  cardInfoLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: appColors.subtitle,
    width: 100,
  },
  cardInfoValue: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    color: appColors.primary,
    textAlign: 'right',
  },
  cardInfoValuePrecio: {
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    color: appColors.green || '#11A679',
    textAlign: 'right',
  },
  cardComentarioBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 8,
    padding: 10,
    backgroundColor: '#F8F9FC',
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: appColors.solideLine || '#ECEEF2',
  },
  cardComentarioIcon: {
    marginRight: 6,
    marginTop: 1,
  },
  cardComentarioContent: {
    flex: 1,
  },
  cardComentarioLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: appColors.subtitle,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  cardComentarioText: {
    fontSize: 12,
    color: '#4B5563',
    lineHeight: 18,
    fontStyle: 'italic',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  serviceName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1F2933',
    flex: 1,
    marginRight: 8,
  },
  statusChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  metaText: {
    fontSize: 12,
    color: appColors.subtitle,
  },
  vehicleText: {
    fontSize: 13,
    color: '#111827',
    marginTop: 8,
  },
  descriptionText: {
    fontSize: 12,
    color: '#4B5563',
    marginTop: 4,
  },
  cardInfoRow: {
    fontSize: 12,
    color: '#4B5563',
    marginTop: 4,
  },
  cardCotizadaBlock: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  cardCotizadaTaller: {
    fontSize: 12,
    fontWeight: '600',
    color: appColors.primary,
    marginBottom: 6,
  },
  cardCotizadaRow: {
    fontSize: 12,
    color: '#4B5563',
    marginTop: 4,
  },
  cardCotizadaValue: {
    fontWeight: '700',
    color: '#111827',
  },
  cardCotizadaComentario: {
    fontSize: 12,
    color: '#4B5563',
    marginTop: 6,
    fontStyle: 'italic',
  },
  cardInspeccionBlock: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  cardInspeccionTaller: {
    fontSize: 12,
    fontWeight: '600',
    color: appColors.primary,
    marginBottom: 6,
  },
  cardInspeccionMessageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 4,
  },
  cardInspeccionMessage: {
    fontSize: 12,
    color: '#4B5563',
    marginLeft: 6,
    flex: 1,
  },
  cancelCardBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  cancelCardBtnText: {
    marginLeft: 6,
    fontSize: 11,
    fontWeight: '700',
    color: '#B91C1C',
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: appColors.primary,
    marginTop: 8,
    marginBottom: 4,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 14,
    color: appColors.subtitle,
    textAlign: 'center',
  },
  cancelModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  cancelModalCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
  },
  cancelModalTitle: {
    marginTop: 10,
    fontSize: 18,
    fontWeight: '800',
    color: appColors.primary,
    textAlign: 'center',
  },
  cancelModalSubtitle: {
    marginTop: 6,
    fontSize: 13,
    color: appColors.subtitle,
    textAlign: 'center',
  },
  cancelModalServiceName: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    textAlign: 'center',
  },
  cancelModalButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 18,
    width: '100%',
  },
  cancelModalSecondaryBtn: {
    flex: 1,
    marginRight: 6,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
  },
  cancelModalSecondaryText: {
    fontSize: 13,
    fontWeight: '600',
    color: appColors.subtitle,
  },
  cancelModalPrimaryBtn: {
    flex: 1,
    marginLeft: 6,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#EF4444',
    alignItems: 'center',
  },
  cancelModalPrimaryText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  detailModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  detailModalCard: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '85%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
  },
  detailModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: appColors.primary,
    marginBottom: 14,
    textAlign: 'center',
  },
  detailModalScroll: {
    width: '100%',
    maxHeight: 280,
  },
  detailModalInspeccionBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: '#FFFBEB',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.4)',
  },
  detailModalInspeccionBannerIcon: {
    marginRight: 10,
    marginTop: 2,
  },
  detailModalInspeccionBannerText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#92400E',
    lineHeight: 21,
  },
  detailModalInspeccionBannerName: {
    fontWeight: '800',
    color: '#78350F',
  },
  detailModalPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    marginBottom: 14,
  },
  detailModalPillText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  detailModalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: appColors.bgLayout || 'rgba(45, 50, 97, 0.06)',
    borderRadius: 10,
    marginBottom: 8,
  },
  detailModalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: appColors.subtitle,
  },
  detailModalValue: {
    fontSize: 13,
    fontWeight: '700',
    color: appColors.primary,
  },
  detailModalValuePrecio: {
    fontSize: 14,
    fontWeight: '800',
    color: appColors.green || '#11A679',
  },
  detailModalTallerLink: {
    marginTop: 2,
    marginBottom: 8,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EAF3FF',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  detailModalTallerLinkText: {
    marginLeft: 6,
    fontSize: 12,
    fontWeight: '700',
    color: "#0000FF",
    textDecorationLine: 'underline',
    textDecorationColor: "#0000FF",
  },
  detailModalComentarioBox: {
    marginTop: 8,
    padding: 12,
    backgroundColor: '#F8F9FC',
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: appColors.solideLine || '#ECEEF2',
  },
  detailModalComentarioLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: appColors.subtitle,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  detailModalComentarioText: {
    fontSize: 12,
    color: '#4B5563',
    lineHeight: 18,
    fontStyle: 'italic',
  },
  detailModalButtonsRow: {
    flexDirection: 'row',
    width: '100%',
    marginTop: 18,
    justifyContent: 'space-between',
  },
  detailModalLoadingWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingVertical: 14,
    gap: 8,
  },
  detailModalLoadingText: {
    fontSize: 13,
    fontWeight: '600',
    color: appColors.subtitle,
  },
  detailModalBtnRechazar: {
    flex: 1,
    marginRight: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    alignItems: 'center',
  },
  detailModalBtnRechazarText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#B91C1C',
  },
  detailModalBtnAceptar: {
    flex: 1,
    marginLeft: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: appColors.green || '#11A679',
    alignItems: 'center',
  },
  detailModalBtnAceptarText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  detailModalTallerProfileBtn: {
    marginTop: 12,
    width: '100%',
    borderRadius: 14,
    backgroundColor: '#FFD60A',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: '#FACC15',
  },
  detailModalTallerProfileIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  detailModalTallerProfileTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1F2344',
  },
  detailModalTallerProfileSubtitle: {
    fontSize: 11,
    color: 'rgba(31,35,68,0.8)',
    marginTop: 2,
  },
  detailModalCerrarLink: {
    marginTop: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  detailModalCerrarText: {
    fontSize: 13,
    fontWeight: '600',
    color: appColors.subtitle,
    textDecorationLine: 'underline',
  },
  successOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17,24,39,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  successCard: {
    width: '100%',
    maxWidth: 390,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 10,
  },
  successIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FFD60A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#FACC15',
  },
  successTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1F2344',
    textAlign: 'center',
  },
  successMainText: {
    marginTop: 8,
    fontSize: 15,
    fontWeight: '800',
    color: '#111827',
    textAlign: 'center',
  },
  successSubText: {
    marginTop: 8,
    fontSize: 13,
    color: '#4B5563',
    textAlign: 'center',
    lineHeight: 20,
  },
  successPrimaryBtn: {
    marginTop: 18,
    width: '100%',
    borderRadius: 14,
    paddingVertical: 12,
    backgroundColor: '#FFD60A',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#FACC15',
  },
  successPrimaryBtnText: {
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '800',
    color: '#1F2344',
  },
  successSecondaryBtn: {
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  successSecondaryBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
    textDecorationLine: 'underline',
  },
});

