import {StyleSheet} from 'react-native';
import {external} from '../../style/external.css';
import {fontSizes, windowHeight, windowWidth} from '../../themes/appConstant';
import {commonStyles} from '../../style/commonStyle.css';

const DARK_BLUE = '#1D1E56';
const YELLOW = '#FFD60A';

const styles = StyleSheet.create({
  // Legacy refs kept for other imports that may use these
  container: {
    ...external.fd_row,
    ...external.pt_10,
    ...external.as_center,
  },
  imgStyle: {
    width: windowWidth(90),
    height: windowHeight(54),
    marginTop: windowHeight(24),
    alignSelf: 'center',
    resizeMode: 'contain',
  },

  // ── Profile Header ────────────────────────────────────────────────────────
  profileHeader: {
    backgroundColor: DARK_BLUE,
    paddingHorizontal: 20,
    paddingBottom: 10,
    alignItems: 'center',
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    borderBottomWidth: 3,
    borderBottomColor: YELLOW,
    shadowColor: DARK_BLUE,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 10,
    overflow: 'hidden',
    position: 'relative',
  },
  headerCircle1: {
    position: 'absolute',
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: 'rgba(255,214,10,0.08)',
    top: -40,
    right: -30,
  },
  headerCircle2: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255,255,255,0.05)',
    bottom: 10,
    left: -20,
  },
  headerTopRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    overflow: 'hidden',
    backgroundColor: '#2D3261',
    borderWidth: 3,
    borderColor: YELLOW,
    marginBottom: 8,
    shadowColor: YELLOW,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 6,
  },
  avatarImg: {
    width: '100%',
    height: '100%',
  },
  statusBadge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  profileName: {
    fontSize: 16,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: 0.2,
    marginBottom: 2,
    lineHeight: 22,
  },
  profileLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileSubtitle: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.5)',
    textAlign: 'center',
  },
  headerDivider: {
    width: '60%',
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    marginBottom: 8,
  },
  profileBtnsRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  profileBtnPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: YELLOW,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 18,
    shadowColor: YELLOW,
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  profileBtnPrimaryText: {
    fontSize: 12,
    fontWeight: '800',
    color: DARK_BLUE,
  },
  profileBtnCancel: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  profileBtnCancelText: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.8)',
  },
  profileBtnSave: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#22C55E',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    shadowColor: '#22C55E',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 3,
  },
  profileBtnSaveText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },

  // ── Scroll / Sections ─────────────────────────────────────────────────────
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 60,
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 8,
    marginBottom: 14,
    shadowColor: '#1F2344',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.05)',
  },

  // ── Section header ────────────────────────────────────────────────────────
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 10,
  },
  sectionHeaderText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#9CA3AF',
    letterSpacing: 1.2,
  },
  sectionHeaderLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#F3F4F6',
  },

  // ── Field display (view mode) ─────────────────────────────────────────────
  fieldDisplayRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    marginBottom: 2,
  },
  fieldDisplayLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  fieldDisplayValue: {
    fontSize: 15,
    fontWeight: '500',
    color: '#1A1F36',
    lineHeight: 22,
  },

  // ── Field edit mode ───────────────────────────────────────────────────────
  fieldWrap: {
    marginBottom: 14,
  },
  fieldLabelTop: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  fieldLabelActive: {
    color: DARK_BLUE,
  },
  fieldRowEditing: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  fieldRowReadonly: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  fieldLabelInline: {
    width: 110,
    fontSize: 13,
    fontWeight: '600',
    color: '#9CA3AF',
    paddingRight: 8,
    lineHeight: 18,
  },
  fieldInputCell: {
    flex: 1,
    minWidth: 0,
  },
  fieldInputEditing: {
    flex: 1,
    minWidth: 0,
  },
  editInput: {
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 44,
    fontSize: 14,
    color: '#111827',
    backgroundColor: '#FAFAFA',
    padding: 0,
  },
  editInputDisabled: {
    backgroundColor: '#F0F1F5',
    borderColor: '#E5E7EB',
    color: '#9CA3AF',
  },

  // ── RIF number input ──────────────────────────────────────────────────────
  rifInput: {
    flex: 1,
    height: 46,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    backgroundColor: '#FAFAFA',
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  rifInputReadonly: {
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
  rifInputText: {
    fontSize: 14,
    color: '#111827',
    padding: 0,
    margin: 0,
  },

  // ── Dropdown ──────────────────────────────────────────────────────────────
  dropdownField: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 10,
    paddingHorizontal: 10,
    minHeight: 46,
    backgroundColor: '#FAFAFA',
  },
  dropdownFieldReadonly: {
    borderColor: '#E9EAEC',
    backgroundColor: '#F5F6FA',
  },

  // ── Segmented control (Agente autorizado) ────────────────────────────────
  segmentedWrap: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  segmentedBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  segmentedBtnActive: {
    backgroundColor: DARK_BLUE,
    borderColor: DARK_BLUE,
  },
  segmentedBtnNo: {
    backgroundColor: '#EF4444',
    borderColor: '#EF4444',
  },
  segmentedBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#9CA3AF',
  },
  segmentedBtnTextActive: {
    color: '#FFFFFF',
  },

  // ── Payment chips ─────────────────────────────────────────────────────────
  pagoHint: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 22,
    paddingVertical: 4,
    marginBottom: 8,
  },
  pagoChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  pagoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  pagoChipActive: {
    backgroundColor: DARK_BLUE,
    borderColor: DARK_BLUE,
  },
  pagoChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
  },
  pagoChipTextActive: {
    color: '#FFFFFF',
  },

  // ── Horarios ──────────────────────────────────────────────────────────────
  horarioDayCard: {
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    backgroundColor: '#FAFAFA',
  },
  horarioDayCardEditing: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D1D5DB',
  },
  horarioDayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  horarioDayLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  horarioDayLabelActive: {
    color: DARK_BLUE,
    fontWeight: '700',
  },
  horarioStatusPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  horarioStatusPillActive: {
    backgroundColor: 'rgba(255,214,10,0.15)',
    borderColor: 'rgba(255,214,10,0.4)',
  },
  horarioStatusText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  horarioStatusTextActive: {
    color: '#92700A',
  },
  horarioTimeRow: {
    flexDirection: 'row',
    marginTop: 10,
  },
  horarioTimeCol: {
    flex: 1,
  },
  horarioTimeLabel: {
    fontSize: 11,
    color: '#6B7280',
    marginBottom: 4,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },

  // ── Map ───────────────────────────────────────────────────────────────────
  mapBox: {
    height: 200,
    borderRadius: 14,
    overflow: 'hidden',
    marginTop: 4,
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.08)',
    marginBottom: 8,
  },

  // ── Documents grid ────────────────────────────────────────────────────────
  docGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 4,
  },
  docThumbBtn: {
    width: '47%',
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#F3F4F6',
    shadowColor: '#1F2344',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  docThumbImg: {
    width: '100%',
    height: 110,
  },
  docThumbOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docThumbLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#374151',
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: '#FFFFFF',
  },
  docEmptyCell: {
    width: '47%',
    height: 140,
    borderRadius: 14,
    backgroundColor: '#F9FAFB',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 8,
  },
  docEmptyCellLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9CA3AF',
    textAlign: 'center',
  },
  docEmptyCellSub: {
    fontSize: 10,
    color: '#D1D5DB',
  },
  docUploadIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: 'rgba(255,214,10,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  docEditBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: DARK_BLUE,
    paddingVertical: 7,
  },
  docEditBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  docNewBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: '#22C55E',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  docNewBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },

  // ── Fullscreen image modal ─────────────────────────────────────────────────
  imgFullBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgFullClose: {
    position: 'absolute',
    top: 52,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  imgFullImage: {
    width: '100%',
    height: '80%',
  },

  // ── Acciones menu modal ───────────────────────────────────────────────────
  menuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  menuCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingBottom: 32,
    paddingTop: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -4},
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 20,
  },
  menuHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E0E4EF',
    alignSelf: 'center',
    marginBottom: 20,
  },
  menuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  menuHeaderIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: DARK_BLUE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: DARK_BLUE,
  },
  menuSubtitle: {
    fontSize: 12,
    color: '#9CA3AF',
    fontWeight: '500',
    marginTop: 1,
  },
  menuOptionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    gap: 12,
    backgroundColor: 'rgba(31,35,68,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(31,35,68,0.07)',
  },
  menuOptionIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuOptionBody: {
    flex: 1,
  },
  menuOptionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: DARK_BLUE,
  },
  menuOptionDesc: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 1,
    lineHeight: 15,
  },
  menuCloseBtn: {
    marginTop: 6,
    paddingVertical: 15,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
  },
  menuCloseBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#6B7280',
  },

  // ── Confirm modal ─────────────────────────────────────────────────────────
  confirmBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  confirmCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
  },
  confirmIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  confirmTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#111827',
    textAlign: 'center',
    marginBottom: 8,
  },
  confirmBody: {
    fontSize: 15,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  confirmBtns: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  confirmBtnCancel: {
    flex: 1,
    marginRight: 6,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    alignItems: 'center',
  },
  confirmBtnCancelText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
  },
  confirmBtnConfirm: {
    flex: 1,
    marginLeft: 6,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  confirmBtnConfirmText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  confirmBtnDisabled: {
    opacity: 0.4,
  },
  confirmInputWrap: {
    width: '100%',
    marginBottom: 20,
  },
  confirmInputLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  confirmInputLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#374151',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  confirmInputRequired: {
    fontSize: 14,
    fontWeight: '800',
    color: '#C62828',
  },
  confirmInput: {
    width: '100%',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    fontSize: 14,
    color: '#1A1F36',
    backgroundColor: '#F9FAFB',
    height: 110,
  },
  confirmInputHint: {
    fontSize: 11,
    color: '#C62828',
    marginTop: 5,
    fontWeight: '500',
  },

  // ── Success modals ────────────────────────────────────────────────────────
  successBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  successCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 12,
  },
  successIconRing: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#BBF7D0',
  },
  successIconInner: {
    width: 66,
    height: 66,
    borderRadius: 33,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#111827',
    textAlign: 'center',
    marginBottom: 10,
  },
  successSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 22,
  },
  successDivider: {
    width: '100%',
    height: 1,
    backgroundColor: '#F3F4F6',
    marginBottom: 20,
  },
  successPromptTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A1F36',
    textAlign: 'center',
    marginBottom: 8,
  },
  successPromptBody: {
    fontSize: 13,
    color: '#9BA6B8',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 22,
  },
  successBtnPrimary: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    borderRadius: 14,
    backgroundColor: '#FFD60A',
    borderWidth: 1.5,
    borderColor: '#FFD60A',
    marginBottom: 10,
  },
  successBtnPrimaryText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1D1E56',
  },
  successBtnSecondary: {
    width: '100%',
    paddingVertical: 13,
    borderRadius: 14,
    alignItems: 'center',
    backgroundColor: '#F4F6FB',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  successBtnSecondaryText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
});

export default styles;
