import { StyleSheet } from 'react-native';

const DARK_BLUE = '#1F2344';
const YELLOW = '#FFD60A';

const styles = StyleSheet.create({
  screenRoot: {
    flex: 1,
  },
  headerArea: {
    marginBottom: 8,
    backgroundColor: DARK_BLUE,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    overflow: 'hidden',
    paddingHorizontal: 24,
    alignItems: 'center',
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderLeftColor: YELLOW,
    borderRightColor: YELLOW,
    position: 'relative',
  },
  headerCircle1: {
    position: 'absolute',
    width: 118,
    height: 118,
    borderRadius: 59,
    backgroundColor: 'rgba(255, 214, 10, 0.14)',
    top: -32,
    right: -24,
  },
  headerCircle2: {
    position: 'absolute',
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    top: 50,
    left: -18,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
  },
  plansLoadingWrap: {
    paddingVertical: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  plansLoadingText: {
    marginTop: 14,
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
  },
  footerWrap: {
    width: '100%',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(31, 35, 68, 0.12)',
  },
  footerInfoOnly: {
    width: '100%',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 18,
    backgroundColor: 'rgba(31, 35, 68, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(31, 35, 68, 0.1)',
  },
  footerBtn: {
    width: '100%',
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 18,
    backgroundColor: YELLOW,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerBtnTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: DARK_BLUE,
    textAlign: 'center',
  },
  footerBtnHint: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(31, 35, 68, 0.78)',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 17,
    paddingHorizontal: 4,
  },
  emptyWrap: {
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: 24,
  },
  emptyIconCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: 'rgba(31, 35, 68, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: DARK_BLUE,
    textAlign: 'center',
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 20,
  },
  planCard: {
    borderRadius: 22,
    marginBottom: 18,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#1F2344',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(31, 35, 68, 0.06)',
  },
  planCardAccent: {
    height: 5,
    width: '100%',
  },
  planCardInner: {
    padding: 18,
    position: 'relative',
  },
  planTopRightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexShrink: 0,
    flexWrap: 'nowrap',
    gap: 8,
  },
  statusPillOuter: {
    flexShrink: 0,
  },
  actualBadge: {
    backgroundColor: YELLOW,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(31, 35, 68, 0.2)',
    flexShrink: 0,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  actualBadgeText: {
    fontSize: 10,
    fontWeight: '900',
    color: DARK_BLUE,
    letterSpacing: 0.8,
  },
  planTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    gap: 8,
  },
  planTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: DARK_BLUE,
    flex: 1,
    flexShrink: 1,
    marginRight: 8,
    letterSpacing: 0.2,
    minWidth: 0,
  },
  statusPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: 'hidden',
  },
  statusText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  statusAprobado: {
    backgroundColor: '#DCFCE7',
  },
  statusAprobadoText: {
    color: '#166534',
  },
  statusPendiente: {
    backgroundColor: '#FEF9C3',
  },
  statusPendienteText: {
    color: '#A16207',
  },
  statusVencido: {
    backgroundColor: '#FEE2E2',
  },
  statusVencidoText: {
    color: '#B91C1C',
  },
  statusDefault: {
    backgroundColor: '#EEF2FF',
  },
  statusDefaultText: {
    color: '#3730A3',
  },
  // ── Servicios strip ───────────────────────────────────────────────────────
  serviciosStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 214, 10, 0.1)',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 10, 0.35)',
    gap: 10,
  },
  serviciosStripIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: YELLOW,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  serviciosStripText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  serviciosStripNum: {
    fontWeight: '900',
    color: DARK_BLUE,
    fontSize: 15,
  },
  infoBlock: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(15, 23, 42, 0.06)',
  },
  datesRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginBottom: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: 'rgba(15, 23, 42, 0.06)',
  },
  dateCell: {
    flex: 1,
    paddingHorizontal: 6,
    alignItems: 'center',
  },
  dateValueText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1E293B',
    textAlign: 'center',
  },
  dateLabelText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 4,
    textAlign: 'center',
  },
  dateDivider: {
    width: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.1)',
    marginVertical: 4,
  },
  dateCellIcon: {
    marginBottom: 6,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoRowLast: {
    marginBottom: 0,
  },
  infoIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 10, 0.35)',
  },
  infoTextCol: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1E293B',
  },
  priceRow: {
    marginTop: 4,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(15, 23, 42, 0.06)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  priceLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748B',
  },
  priceValue: {
    fontSize: 22,
    fontWeight: '800',
    color: DARK_BLUE,
  },
  priceCurrency: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748B',
    marginLeft: 4,
  },
  priceWrap: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  freeBadge: {
    marginLeft: 8,
    backgroundColor: 'rgba(255, 214, 10, 0.25)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  freeBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#854D0E',
  },
});

export default styles;
export { DARK_BLUE, YELLOW };
