// eslint-disable-next-line no-undef
export default Images = {
  productImageOne: require('../assets/images/homeScreenOne/Content/productImage1.png'),
  productImageTwo: require('../assets/images/homeScreenOne/Content/productImage2.png'),
  productImageThree: require('../assets/images/homeScreenOne/Content/productImage3.png'),
  // homeBannerTwo: require('../assets/images/homeScreenOne/bannerTwo.png'),
  // homeBannerThree: require('../assets/images/homeScreenOne/bannerThree.png'),
  test: require('../assets/images/homeTwo/test.jpg'),
  test1: require('../assets/images/homeTwo/test1.jpg'),
  test2: require('../assets/images/homeTwo/test2.jpg'),
  test3: require('../assets/images/homeTwo/test3.jpg'),
  loaderBg: require('../assets/images/signUp/loaderBg.png'),
  beg: require('../assets/images/signUp/bag.gif'),
  darkBag: require('../assets/images/darkModeGIF/darkEmpty.gif'),
  notification: require('../assets/images/signUp/notification.gif'),
  visa: require('../assets/images/profile/visa.png'),
  apple: require('../assets/images/profile/apple.png'),
  gpay: require('../assets/images/profile/gpay.png'),
  masterCard: require('../assets/images/profile/masterCard.png'),
  profileOne: require('../assets/images/profile/Profile-1.png'),
  profileTwo: require('../assets/images/profile/Profile-2.png'),
  profileThree: require('../assets/images/profile/Profile-3.png'),
  profileFour: require('../assets/images/profile/Profile.png'),
  delete: require('../assets/images/profile/delete.gif'),

  productImage: require('../assets/images/productDetail/productImageOne.png'),
  productImage_3: require('../assets/images/productDetail/productImageThree.png'),
  productImage_4: require('../assets/images/productDetail/productImageFour.png'),
  loaderBgDark: require('../assets/images/signUp/loaderBgDark.png'),
  loading: require('../assets/images/signUp/loadingSolversNew.gif'),
  DarkNotification: require('../assets/images/darkModeGIF/darkNotification.gif'),
};
