import {StyleSheet} from 'react-native';
import {fontSizes, windowHeight, windowWidth} from '../../themes/appConstant';
import appColors from '../../themes/appColors';
import {external} from '../../style/external.css';
import {commonStyles} from '../../style/commonStyle.css';
const styles = StyleSheet.create({
  screenRoot: {
    flex: 1,
    backgroundColor: '#1F2344',
  },
  perimeterTopArea: {
    flex: 1,
    backgroundColor: '#1F2344',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
    overflow: 'hidden',
  },
  headerCircle1: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(255,214,10,0.12)',
    top: -30,
    right: -20,
  },
  headerCircle2: {
    position: 'absolute',
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: 'rgba(255,255,255,0.10)',
    top: 52,
    left: -14,
  },
  perimeterHeaderBlock: {
    paddingTop: 8,
    paddingBottom: 28,
    paddingHorizontal: 4,
  },
  perimeterTitle: {
    fontSize: 30,
    fontWeight: '900',
    color: '#FFD60A',
    textAlign: 'center',
    lineHeight: 38,
    marginBottom: 14,
  },
  perimeterSubtitle: {
    fontSize: 16,
    color: '#e8eaf6',
    textAlign: 'center',
    lineHeight: 24,
    opacity: 0.98,
    paddingHorizontal: 8,
    marginBottom: 8,
  },
  perimeterBottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 60,
    borderTopRightRadius: 60,
    paddingTop: 20,
    paddingHorizontal: 30,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -2},
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  perimeterScrollContent: {
    paddingBottom: 120,
  },
  profileCard: {
    marginTop: 0,
    marginHorizontal: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    shadowColor: '#1F2344',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.13,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#E6EAF5',
  },
  avatarFrameOuter: {
    width: 118,
    height: 118,
    borderRadius: 59,
    backgroundColor: '#EAF0FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFrameInner: {
    width: 106,
    height: 106,
    borderRadius: 53,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#FFD60A',
  },
  container: {
    marginVertical: windowHeight(7),

    flexDirection: 'row',
    borderColor: appColors.cardBorder,
    borderRadius: windowHeight(8),
    padding: 1,
    elevation: 1,
    shadowColor: appColors.shadowColor,
    margin: 1,
  },
  imgStyle: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  viewContainer: {
    ...external.pt_0,
    ...external.ph_0,
    ...external.fx_1,
    backgroundColor: '#F5F6F8',
  },
  titleText: {
    ...commonStyles.titleText19,
    color: '#1F2344',
    fontSize: fontSizes.FONT17,
    fontWeight: '700',
    flexShrink: 1,
    lineHeight: 22,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  nameText: {
    ...commonStyles.H1Banner,
    ...external.ti_center,
    paddingTop: 10,
    fontSize: fontSizes.FONT22,
    color: '#1F2344',
    fontWeight: '900',
  },
  emailText: {
    marginTop: 2,
    color: '#5D668A',
    fontSize: fontSizes.FONT16,
    textAlign: 'center',
  },
  userTypeBadge: {
    marginTop: 10,
    backgroundColor: '#1F2344',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 14,
  },
  userTypeBadgeText: {
    color: '#FFD60A',
    fontWeight: '800',
    fontSize: fontSizes.FONT14,
  },
  grayBorder: {
    borderWidth: windowHeight(7),
    width: windowHeight(70),
    height: windowHeight(70),
    alignSelf: 'center',
    borderRadius: windowHeight(70),
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#EBEEFD',
    marginTop: windowHeight(15),
  },
  primaryBorder: {
    borderWidth: 2,
    width: windowHeight(60),
    height: windowHeight(60),
    alignSelf: 'center',
    borderRadius: windowHeight(60),
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#2D3261',
  },
  menuItemContent: {
    alignItems: 'center',
    flexDirection: 'row',
    width: '100%',
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 16,
  },
  menuSection: {
    marginTop: 14,
    paddingHorizontal: 0,
    paddingBottom: 24,
  },
  optionCardOuter: {
    marginBottom: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E9EDF5',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  optionCardOuterPressed: {
    opacity: 0.9,
  },
  optionCardInner: {
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  optionRow: {
    alignItems: 'center',
    width: '100%',
    minHeight: 56,
    justifyContent: 'space-between',
  },
  optionIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1F2344',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  optionTitleWrap: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
    justifyContent: 'center',
  },
  optionArrowWrap: {
    width: 22,
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginLeft: 8,
  },
  optionArrowCircle: {},
  optionArrowWrapLegacy: {},
});

export default styles;
