import { StyleSheet, Platform } from 'react-native';
import appColors from '../../themes/appColors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F6F8',
  },
  scrollContent: {
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#EEF0F2',
  },
  backBtn: {
    padding: 8,
    marginRight: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: appColors.primary,
  },
  headerSubtitle: {
    fontSize: 13,
    color: appColors.subtitle,
    marginTop: 2,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1D26',
    marginBottom: 14,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  labelRequired: {
    color: appColors.red,
  },
  input: {
    backgroundColor: '#F9FAFB',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#1A1D26',
    minHeight: 48,
    borderWidth: 0,
  },
  inputMultiline: {
    minHeight: 100,
    textAlignVertical: 'top',
    paddingTop: 14,
  },
  dropdown: {
    backgroundColor: '#F9FAFB',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 4,
    minHeight: 48,
    borderWidth: 0,
  },
  dropdownPlaceholder: {
    color: '#9CA3AF',
    fontSize: 15,
  },
  dropdownSelectedText: {
    color: '#1A1D26',
    fontSize: 15,
  },
  charCount: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 4,
    textAlign: 'right',
  },
  charCountError: {
    color: appColors.red,
  },
  photoRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 8,
  },
  photoAddBtn: {
    width: 80,
    height: 80,
    borderRadius: 14,
    backgroundColor: '#E8F4FD',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: appColors.primary,
  },
  photoThumb: {
    width: 80,
    height: 80,
    borderRadius: 14,
    backgroundColor: '#E5E7EB',
  },
  photoRemove: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: appColors.red,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  locationRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    marginTop: 8,
  },
  locationInput: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#1A1D26',
  },
  locationActionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
    flexWrap: 'wrap',
  },
  gpsBtn: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: appColors.primaryLight,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  mapBtn: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#F3F4F6',
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  urgenciaRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  urgenciaOption: {
    flex: 1,
    minWidth: '30%',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  urgenciaOptionSelected: {
    backgroundColor: '#E8F4FD',
    borderColor: appColors.primary,
  },
  urgenciaOptionUrgente: {
    backgroundColor: '#FFF7ED',
    borderColor: '#EA580C',
  },
  urgenciaOptionEmergencia: {
    backgroundColor: '#FEF2F2',
    borderColor: appColors.red,
  },
  urgenciaLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
  },
  submitBtn: {
    marginTop: 28,
    borderRadius: 16,
    paddingVertical: 16,
    backgroundColor: '#FFD60A',
    alignItems: 'center',
    shadowColor: appColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  submitBtnDisabled: {
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0,
  },
  submitBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: appColors.primary,
  },
  vehicleCard: {
    backgroundColor: '#E8F4FD',
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderLeftWidth: 4,
    borderLeftColor: appColors.primary,
  },
  vehicleIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(45, 50, 97, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  vehicleTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1D26',
  },
  vehicleSub: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 2,
  },
  errorText: {
    fontSize: 12,
    color: appColors.red,
    marginTop: 4,
  },
  mapModalContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  mapHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  mapCloseBtn: {
    padding: 8,
    marginRight: 8,
  },
  mapHeaderTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: appColors.primary,
  },
  map: {
    flex: 1,
  },
  mapFooter: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    paddingBottom: 28,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  mapConfirmBtn: {
    borderRadius: 16,
    paddingVertical: 14,
    backgroundColor: '#FFD60A',
    alignItems: 'center',
  },
  mapConfirmBtnDisabled: {
    backgroundColor: '#9CA3AF',
  },
  mapConfirmText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A1D26',
  },
  locationCard: {
    marginTop: 8,
    backgroundColor: '#EEF4FF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#C7D8FF',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#DCE8FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  locationTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 1,
  },
  locationCoords: {
    fontSize: 12,
    color: '#475569',
  },
  locationSelectBtn: {
    backgroundColor: '#2D3261',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginLeft: 8,
  },
  locationSelectBtnText: {
    color: '#FFD60A',
    fontSize: 12,
    fontWeight: '700',
  },
  locationTakenBadge: {
    backgroundColor: '#DCFCE7',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  locationTakenText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#16A34A',
    letterSpacing: 0.2,
  },
  mapOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  mapSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    minHeight: 420,
  },
  mapSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mapSheetTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1D26',
  },
  mapSheetCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapSheetFullScreenBtn: {
    padding: 6,
    marginLeft: 8,
    borderRadius: 10,
    backgroundColor: '#EEF2FF',
  },
  mapSheetSubtitle: {
    marginTop: 6,
    color: '#6B7280',
    fontSize: 13,
    lineHeight: 18,
  },
  mapMockArea: {
    marginTop: 14,
    height: 220,
    borderRadius: 18,
    backgroundColor: '#E6F0FF',
    borderWidth: 1,
    borderColor: '#CFE0FF',
    overflow: 'hidden',
    position: 'relative',
  },
  mapGridOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 0,
    backgroundColor: 'rgba(45, 50, 97, 0.05)',
  },
  mapCoordsBox: {
    marginTop: 12,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  mapCoordsText: {
    fontSize: 13,
    color: '#334155',
    textAlign: 'center',
    fontWeight: '600',
  },
  mapApplyBtn: {
    marginTop: 14,
    backgroundColor: '#FFD60A',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  mapApplyBtnText: {
    color: '#1A1D26',
    fontSize: 15,
    fontWeight: '800',
  },
  mapFullScreenContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  mapFullScreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 54 : 20,
    paddingBottom: 14,
    backgroundColor: '#1D1E56',
  },
  mapFullScreenTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '800',
    color: '#FFD60A',
  },
  mapFullScreenMap: {
    flex: 1,
  },
  confirmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  confirmCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 28,
    paddingHorizontal: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 16,
  },
  confirmIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#FFF8E6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  confirmTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1A1D26',
    textAlign: 'center',
    marginBottom: 6,
  },
  confirmSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
    paddingHorizontal: 8,
  },
  confirmSummary: {
    width: '100%',
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  confirmRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  confirmLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
    width: '32%',
  },
  confirmValue: {
    fontSize: 13,
    color: '#1A1D26',
    flex: 1,
    textAlign: 'right',
  },
  confirmActions: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  confirmCancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
  },
  confirmCancelText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#6B7280',
  },
  confirmSubmitBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#FFD60A',
    alignItems: 'center',
  },
  confirmSubmitText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1D26',
  },
  successOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  successCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 16,
  },
  successIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#e7f6f2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
  },
  successTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1A1D26',
    textAlign: 'center',
    marginBottom: 10,
  },
  successMessage: {
    fontSize: 15,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  successBtn: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#FFD60A',
    alignItems: 'center',
  },
  successBtnText: {
    fontSize: 16,
    fontWeight: '700',
    color: appColors.primary,
  },
});
